### ISSUE TITLE
How to interpret error "ICE/STUN response received, but source address didn't match remote candidate address (from clientip:51758 on interface ourip:36804)"

### ISSUE THREAD

**Issue by elbow** [sipwise/rtpengine#1040]
Hi,

I'm seeing the error as above in my rtpengine logs.

My environment is simple - the box running rtpengine has a public IP - in testing  the <clientip> is the address I would expect from the client side (the client's "public" IP) and the <ourip> is the IP of the box running rtpengine.

I see
```
ICE/STUN response received, but source address didn't match remote candidate address (from <clientip>:51758 on interface <ourip>:36804)
```

Is there another address that is being interrogated that isn't shown here? Looking in the code I see the error display is generic for a bunch of tests.

I do have a turn server on a different IP and I'm not sure if that could be involved?

**Comment by rfuchs** [comment]
That's a requirement of the ICE/STUN protocol as explained in https://tools.ietf.org/html/rfc5245#section-7.1.3 in particular section 7.1.3.2. If a connectivity check is sent to address X port Y, then the response must be received from the same address X port Y. Otherwise the check must be considered a failure, and this is what you see happening. If you turn on debug logging, you should see where the response is received from. You can also run a packet dump (Wireshark etc) to see it in even more detail.

**Comment by elbow** [comment]
Ah - I think I understand - can you check my understanding:

This ICE/STUN response is not acceptable exactly because if has been NATted on the way.
The client side found both its local and an srflx address using STUN
We will receive response both with the local address (but natted to the public),
and with the srflx address - which is the public address (and due to natted arriving from that same address).

We must take the srflx address and drop the local address in this case with nat between the client and rtpengine?

In summary:

```
Jul 15 15:09:31 ct-kamdev rtpengine[24456]: DEBUG: [5402c59d646755c9772e00ef584b96f4@AAA.BBB.250.134:5060 port 16466]: Received ICE/STUN response code 0 for candidate pair pUuZBkCj41V48P57:2365191058:1 from 10.64.16.132:64793 to AAA.BBB.250.154
Jul 15 15:09:31 ct-kamdev rtpengine[24456]: NOTICE: [5402c59d646755c9772e00ef584b96f4@AAA.BBB.250.134:5060 port 16466]: ICE/STUN response received, but source address didn't match remote candidate address (from AAA.BBB.17.6:64793 on interface AAA.BBB.250.154:16466)
Jul 15 15:09:31 ct-kamdev rtpengine[24456]: DEBUG: [5402c59d646755c9772e00ef584b96f4@AAA.BBB.250.134:5060 port 16466]: Received ICE/STUN response code 0 for candidate pair pUuZBkCj41V48P57:2062125638:1 from AAA.BBB.17.6:64793 to AAA.BBB.250.154
Jul 15 15:09:31 ct-kamdev rtpengine[24456]: DEBUG: [5402c59d646755c9772e00ef584b96f4@AAA.BBB.250.134:5060 port 16466]: Setting ICE candidate pair pUuZBkCj41V48P57:2062125638:1 as succeeded
Jul 15 15:09:31 ct-kamdev rtpengine[24456]: DEBUG: [5402c59d646755c9772e00ef584b96f4@AAA.BBB.250.134:5060 port 16466]: Best succeeded ICE pair with all components is pUuZBkCj41V48P57:2062125638:1
```

Anyway - with another test and with issue #1038 dealt with I see that my call sets up fine.

Here's the trace of this case:

[rtpengine-latest-master-using-dtls=on-in-answer.log](https://github.com/sipwise/rtpengine/files/4925514/rtpengine-latest-master-using-dtls.on-in-answer.log)

Thanks very much for your assistance.

**Comment by rfuchs** [comment]
The issue is not the NAT itself. NAT addresses are detected and supported through srflx and prflx and due to the fact that the addresses are carried within the STUN packets. But: the NAT must be symmetric. Meaning that the address translation you get going in must be the opposite of the address translation you get going out. This is a requirement as per the ICE specification.

This is only relevant to STUN connectivity checks that rtpengine sends out. Concrete example: Rtpengine sends an STUN request to destination 203.0.113.1 port 4444. There's a NAT in between and the destination address is rewritten to 10.0.0.1 port 5555. So the remote client listens on 10.0.0.1 port 5555 and there receives the STUN request from rtpengine. The remote client now sends a response do that. It sends the response from its local source address 10.0.0.1 port 5555 back to rtpengine. On the way out, it passes the NAT again and the NAT rewrites the source address 10.0.0.1 port 5555 back to 203.0.113.1 port 4444. Rtpengine then receives the STUN response with a source address 203.0.113.1 port 4444, which is the same as the destination address that it originally sent the request to. That's would be a successful STUN check.

A malfunctioning NAT might rewrite the source address of the STUN response going back to rtpengine to something different. So if the NAT takes the STUN response and rewrites the source address to say 203.0.113.1 port 6666, then rtpengine would receive the STUN response with a source address of 203.0.113.1 port 6666, which would be different from the destination address that it originally sent the STUN request to (same address but port 4444). That would be an STUN failure and would issue the log line you see.

**Comment by elbow** [comment]
> A malfunctioning NAT might rewrite the source address of the STUN response going back to rtpengine to something different. So if the NAT takes the STUN response and rewrites the source address to say 203.0.113.1 port 6666, then rtpengine would receive the STUN response with a source address of 203.0.113.1 port 6666, which would be different from the destination address that it originally sent the STUN request to (same address but port 4444). That would be an STUN failure and would issue the log line you see.

Aha - then I think I should explain the network topology in more detail.

1. I have a tunnel from here at home to our core.  It makes those 10.64.16.0/24 addresses directly reachable from the location of the rtpengine without NAT.
2. On my side I usually route the relevant public addresses rtpengine is using via that tunnel
3. But to investigate this issue I removed that route on my home network.

The result is that traffic from my client gets natted on the way out.  But the rtpengine side can actually still reach the 10.64.16 address directly.

Reading between the lines it would appear that RTPengine then sent a stun connectivity check directly to 10.64.16.104 - the address it found in the "local" candidate? and the actual address of my client device.  Because 10.64.16 is reachable from the rtpengine it would have arrived un-natted.

But the reply would have come natted from aaa.bbb.17.6 my home public IP.

Which would have created the address discrepancy and you are 100% right to drop the candidate.

Do I have it?

**Comment by rfuchs** [comment]
Sounds like you have asymmetric routing and a NAT only in one direction. So yes, that would explain it, and ICE forbids usage of connectivity like that. You can do a packet trace with Wireshark on the rtpengine host to fully confirm.
