### ISSUE TITLE
Question on Debug: timer run time = 0.00000n

### ISSUE THREAD

**Issue by githubsw** [sipwise/rtpengine#1065]
Hello,

I have rtpengine installed and working great on different OS's.  I have however noticed that on Amazon Linux 2 that I never see the debug message in question even though things seem to be working fine.  I thought it might be a version issue but when I look at the version with --version, I either see 'undefined' or 'Version : git-master-yyyyyy".  Does anyone know the cause of either of these issues?  Is there a way to see find the actual version?

Thank you,

**Comment by rfuchs** [comment]
The `yyyyyyy` would be the git commit ID, so from that you can tell the version. If `undefined` then it must have been a build that was done outside of a git and/or Debian environment. In that case there's not much you can do about it since the version is taken from the git tree or the Debian changelog at build time.
