### ISSUE TITLE
metadata not saved when using "proc" recording-method

### ISSUE THREAD

**Issue by ivlovric** [sipwise/rtpengine#1084]
Hi,

I am using rtpengine mr8.4.1.1 and trying to get metadata saved to file along with my recordings. I just found that metadata is saved correctly when using "raw" method but not "proc" method with exact same scenario. I am initiating recording from Opensips 3.0 

log when "proc" method is enabled
[proc.txt](https://github.com/sipwise/rtpengine/files/5293874/proc.txt)
log when "raw" method is enabled
[raw.txt](https://github.com/sipwise/rtpengine/files/5293876/raw.txt)

**rtpengine conf**
```
[rtpengine]

table = 0

interface = 10.116.118.94
listen-ng = 127.0.0.1:12222

timeout = 60
silent-timeout = 3600
tos = 184

max-cpu = 90

port-min = 30000
port-max = 40000

recording-dir = /var/spool/rtpengine
recording-method = proc

 log-level = 6
 log-facility = local6
```

**rtpengine-recording conf**
```
`[rtpengine-recording]

table = 0

log-facility=local6

 output-format = mp3

 spool-dir = /var/spool/rtpengine

 output-dir = /var/lib/rtpengine-recording

 output-mixed = true

 output-single = true`
```

**Comment by rfuchs** [comment]
You're talking about the metadata file that has content like "Timestamp started ms: ..." etc?

**Comment by ivlovric** [comment]
Yes, metadata file is not written to be more specific. We are interested in additional metadata that we need in files for better post processing. But with database backend enabled for example, metadata is correctly written to database in case of "proc" method recording.

Today I tried with rtpengine branch 7 and with latest 9.0.1.1 but with no luck.

Thanks a lot!

**Comment by rfuchs** [comment]
Ok yeah, so this is actually by design: the metadata file you're referring to is specific to the pcap recording method and isn't used in the proc method at all. For that, there's a different kind of metadata file, but that one's actually used to control the recording daemon. Actual metadata is then written to the database by the recording daemon.

The two recording methods are quite distinct and the proc method just doesn't support a metadata file in the same way. You should look into extending the metadata writing capabilities in the recording daemon, e.g. more detail into the database, or to a file instead of to the database.

**Comment by ivlovric** [comment]
Thank you for your answer, that clears many things I haven't been able to find more detail about in rtpengine documentation.
We will try to examine the code and if there is any real progress, I guess PR should be reasonable :)

Thanks, this "issue" can be closed now.
