### ISSUE TITLE
Codec renegotiation after rtp session is established

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1102]
Dear all,

is it possible to do codec renegotation after the rtp session is established with rtpengine flags or something?
Procedure is:

INVITE (Kamailio) -->
G711A
G711U
G729 (with rtpengine transcoding engine)

<-- SESSION PROGRESS (customer SBC)
G711A

RTP Session is established with G711A, when call is picked up:

<-- OK (customer SBC)
G729

ACK (kamailio) -->

After pick up there is no way media, because kamailio wants g711 and customer sends g729 and vice versa
It seems like customer sbc doesn't support re-invite in this case..

I guess i could do it by saving sdp in xavps and doing manual offer/answer when this scenario occurs, but is there a possibility to allow this per flag in rtpengine_manage or something like that (though i didn't find anything in the documentation)?

Thanks in advance

**Comment by rfuchs** [comment]
I believe this should work out of the box as long as the SDP flow is correctly signalled to rtpengine. Enable log level 7 and post the log of such a scenario to find out.

**Comment by thomas414** [comment]
Thank you, debug log is attached with the important parts, please let me know if you need more. Just for your information, ip addresses were replaced.

[rtpengine-debug.txt](https://github.com/sipwise/rtpengine/files/5481864/rtpengine-debug.txt)

**Comment by rfuchs** [comment]
Ok, so in this log the transcoding engine isn't even actually enabled because G.729 was already present in the incoming offer. So the `codec-transcode-G729` flag doesn't actually do anything because the codec was already supported. Subsequently, both answers are simply passed through unchanged.

What would you expect to happen here instead?

**Comment by malvarado611** [comment]
Could you help me with an example of how to implement what you say please

**Comment by malvarado611** [comment]
If I had different tables running the same IP, but different ports with different paths to save the recordings, it could help me by commenting above.

**Comment by thomas414** [comment]
Hi, after removing G729 in the incoming offer we now have one way audio

Does work: kamailio <--- customer SBC
Does not work: kamailio ---> customer SBC (still sending PCMA)

I see in the debug log that the transcoding engine is enabled for the initial offer
`Created transcode context for G729/8000 -> PCMA/8000 with DTMF output 101`

Then i hear early media which is using PCMA.
After the second answer comes from the customer SBC there is only transcoding from G729 to G729 but not PCMA to G729 (we enabled `always-transcode` for testing, but it is the same with or without the flag).

We also tried stripping G729 `codec-strip=g729` and manually transcoding to PCMA `codec-transcode=PCMA` for the answers coming from customer SBC, but that didn't change anything.

While reading through the debug log i saw these two lines:
`Eliminating asymmetric outbound codec PCMA/8000`
`Eliminating asymmetric outbound codec PCMU/8000`
but after using the flag `asymmetric-codecs` the two lines just disappeared but no change in functionality.

Maybe I am just getting something fundamentally wrong here..

Debug log where all of the above mentioned applied is attached, but i saved all the other logs so if you need them too i can send them to you

[rtpengine_debug_one_way_audio.txt](https://github.com/sipwise/rtpengine/files/5495000/rtpengine_debug_one_way_audio.txt)

Many thanks in advance!

**Comment by rfuchs** [comment]
The problem is that the second answer is coming from a different to-tag than the first answer. So this is seen as coming from a different RTP peer, one for which transcoding wasn't established because there was no offer towards it. This use case isn't currently support. If this is a branched call, you need to issue two offers to rtpengine, with different via-branch strings, so rtpengine knows that there are two RTP peers involved, and which one the answer is coming from.

If this is not a forked call (on your end), a workaround is to make sure the to-tag is the same in both answers, or just ignore early media answers.

**Comment by thomas414** [comment]
This is a forked call, after adding `via-branch=auto` flag it seems to work!

Tank you very much!!
