### ISSUE TITLE
Question about DTMF Transcoding

### ISSUE THREAD

**Issue by thomas414** [sipwise/rtpengine#1123]
I have a quick question about dtmf transcoding, basically rtpengine is set to transcode inband to rfc2833 in the incoming direction and rfc2833 to inband in the outgoing direction.

inband <-> rtpengine <-> rfc2833

While rtpengine is transcoding inband to rfc2833, there are still a few packets of inband tone left in the rtp stream until the tone is cut out, when the same rtp stream is then going through rtpengine in the outgoing direction (where rfc2833 is transcoded to inband) i have double inband dtmf tones in the rtp stream, the few packets from the incoming direction and the transcoded ones for the outgoing direction. Unfortunately this is enough to be treated as two different dtmf tones.

I also think that this is a time problem because i guess rtpengine needs at least two or three packets to detect dtmf tones, but because these are already sent out to the destination until rtpengine starts transcoding there is nothing that rtpengine can do.

My question is if anybody else is having problems with this scenario and can tell me how they handle it, or if there is even a solution within rtpengine i don't know about?

Regards
Thomas

**Comment by rfuchs** [comment]
This is due to how the DSP to detect DTMF works: The DSP requires a minimum run-in time before the DSP is able to detect a DTMF tone as such. By the time the DSP kicks in and detects the DTMF event, some samples would have already passed as regular audio, undetected as part of the DTMF event.

Generally speaking, the in-band PCM to RFC transcoding is meant for RTP peers which cannot detect in-band DTMF tones and rely on RFC events. If your remote peer is able to detect in-band DTMF (and still does so even if offered RFC events), then I would think you should be able to just skip on the DTMF transcoding and leave the tones in-band, no?

**Comment by thomas414** [comment]
Thank you for the clarification, we are now doing transcoding dynamically on a per call basis and can leave in-band in for this special case, which works much better!
