### ISSUE TITLE
RTPengine STUN/ICE websocket.

### ISSUE THREAD

**Issue by acthard** [sipwise/rtpengine#1146]
A quick summary of the topology. WEBSOCKET Application >>> FIREWALL PortFwd RTP Traffic >> RTP Engine. 
                                                                                                >>> FIREWALL PortFwd WEBSOCKET >>> PBX

I see there are settings for the RTPENGINE to handle ICE/STUN requests is this possible with a stand alone rtpengine server?

**Comment by rfuchs** [comment]
If your websocket application supports ICE, then you can use ICE to negotiate the media path between the application and rtpengine. If the two are able to communicate with each other in any way (NAT or not) then ICE should be able to make media flow. External STUN/TURN servers are only needed if both application and rtpengine are behind NAT or otherwise shielded from each other.
