### ISSUE TITLE
Homer seems to block main thread and DNS caches longer than TTL

### ISSUE THREAD

**Issue by nathanleyton** [sipwise/rtpengine#1215]
We were having issues with latency in rtp and other failures under load, and we found that it was due to stress on homer rather than stress on rtpengine, issues fixed by improving throughput to homer (tcp is now the default for homer 7). IMO it would be better if homer was a worker, processing the queue rather than off the main thread. If it is already then there is some other bug going on. 

Also I found that all calls hung after I updated our homer node, as it was assigned a new IP address and the DNS didn't update in rtpengine, the errors continued about sending to homer on the old IP address. The fact this totally brought down rtpengine must  mean its on the main processing thread. It would be also good though if we use a hostname that rtpengine respects TTL on the domain. Using the OS DNS resolution would work, as I did check using dig at the time rtpengine was still reporting errors on the old IP and the OS had the correct IP address for homers host name. Perhaps it is planned as I see in your doc's:-

`If DNS host names are used instead of addresses or interface names, the lookup will be done only once during daemon start-up.`

Perhaps this is good for the interfaces as they are really not likely to change, however, we have auto scaling and multiple ip and load balanced DNS for homer end points so for this case it would really help if it used the OS, DNS. 

I have managed to work around these issues but thought to report and see if any of my assumptions are correct, C is not my language, so looking at the code I wasn't 100% sure but it did seem that homers queue / memory was started on the main.c in the main thread and also seemed there was a lock on some objects within that code. 

Thanks in advance for any time spent on this.

**Comment by rfuchs** [comment]
So you're right that the Homer code is directly called from the main packet processing threads, but AFAICT all the sending code in homer.c is non-blocking. Going through the code I don't really see a place where it could possibly block. Regardless of whether the connection is already established or not, or whether the Homer receiver can keep up with the sent data, it should never block. (This is part of the reason why the DNS lookup is done at startup only, because doing non-blocking DNS requires some extra effort.)

So unless there's a hidden bug lurking somewhere, I'd say there's something else going on.

**Comment by rfuchs** [comment]
Cleaning up old tickets
