### ISSUE TITLE
audio recording without in-kernel packet forwarding

### ISSUE THREAD

**Issue by alexwqr** [sipwise/rtpengine#1228]
I wonder if I can run rtpengine without in-kernel packet forwarding (--table=-1) and then generate audio recording with wav format as well.
I know in-kernel packet forwarding with the help of rtpengine-recording can achieve that, but my Environment cannot enable in-kernel package forwarding and I really hope to generate audio recording with wav format rather than pcap file.

Thanks a lot.

**Comment by rfuchs** [comment]
Unfortunately that's not supported right now. Pull requests welcome.

**Comment by alexwqr** [comment]
thanks for your quick reply.  My environment is 32bit which is not supported by kernel module. Could you please point out the code where rtpengine receives RTP packages?  Maybe I can send them out via multicast then I can use gstreamer to re-catch&decode into wav file.

**Comment by rfuchs** [comment]
The kernel module should work fine on 32 bit. If it doesn't then submit a bug report (or better yet a pull request).

The relevant code is in recording.c for the main daemon - you could duplicate most of the "proc" functions, but instead of using `setup_stream_proc` to get a kernel-side interface for sending packets to, you could open a local interface like a datagram unix socket or maybe a named pipe. The function to actually write packets into the interface is `dump_packet_proc`

On the recording daemon side, everything relevant is in stream.c - here you would just need to open the file to read from in a different way (e.g. read from a socket instead of opening a file and then reading from that).

Or you can add a completely different recording method like the "pcap" one, but instead of writing the packets to a pcap you do something else with them.

**Comment by rfuchs** [comment]
Cleaning up old tickets
