### ISSUE TITLE
Avoid 'no media' when 183 not followed by rtp.

### ISSUE THREAD

**Issue by dvillaume** [sipwise/rtpengine#1273]
Hello,

We often notice on ougoing calls systems that sends 183 SDP with, but never send rtp after.
This is something that seems more and more common du to full sip interconnections.

I tried to find a way to hide this from customer perspective and thought we could initiate a 'play' with country based ringback files and add an option that would break playback in case media is received on the corresponding leg.

Do you think this could work and be usefull to comunity ? if so i can have a look to prepare a PR about it.

Regards,
David

**Comment by rfuchs** [comment]
Sure, feel free, and don't hesitate to ask if you have questions about the implementation.

**Comment by rfuchs** [comment]
When starting media playback: Make sure the stream forwarding does not happen in the kernel (because the daemon needs to see incoming packets): you can use `__call_unkernelize()` for that.

Upon receiving a packet in `stream_packet()`: check the output side of the forwarding chain (the sink): if the sink monologue has an active media player which is flagged to stop playback when a packet is seen, stop the playback. There's a locking issue here, as `stream_packet` only holds a read-lock on the call, but stopping the player requires a write-lock. So I would flag this condition and delay processing until the end of `stream_packet` where the lock is released, then the write-lock can be acquired and the player can be stopped.

**Comment by rfuchs** [comment]
Cleaning up old tickets
