### ISSUE TITLE
Packetloss on high Load after Upgrade from mediaproxy-ng

### ISSUE THREAD

**Issue by qmex-mp** [sipwise/rtpengine#128]
Hi,

Setup:
Kamailio Machine with 8 CPU Cores, handling about 3000 - 4000 concurrent Calls.

Old Setup:
Kamailio 4.1 and Mediaproxy-NG

New Setup:
Kamailio 4.2 and rtpengine with and without in kernel forwarding

A few weeks ago, we updated our Core Router from the old Setup to the new, in other words: Update from Kamailio 4.1 and mediaproxy-ng to Kamailio 4.2 and rtpengine (first time in userspace mode, like mediaproxy-ng before).

First impression:
rtpeingine has like 1.5 / 2 times the Load of mediaproxy-ng in the same Environment. We had some packetloss on the high load time, and thought, because now, there are 6,5 of 8 CPU Cores used, it must be the high load (system load was between 1 and 2). So we changed the Setup to in kernel forwarding. Now we are using a little bit more than 1 CPU Core, but in the same high load situation, Nagios and an MTR shows like 10 - 20 % Packetloss and it doesnt look like a Network problem, because all other VMs on the Same Machine are fine (we use a 10 GBit NIC with XEN and SR-IOV, so Network is not a problem).

Could it be possible that the Linux Network stack or iptables is a bottle neck? Could this be a bug or is there space for enhancements like in sysctl.conf?

**Comment by rfuchs** [comment]
Unfortunately I don't have a good answer for you. The in-kernel part is largely unchanged between the two versions and there's no reason why one should exhibit significantly lower performance or higher packet loss than the other. The IP stack should be able to handle everything up to the limits of the hardware. However, I can't vouch for performance when running in a VM. I'm not saying that this is the reason for your problems, but that it's something to consider and it's worth to try running it on "real" hardware.

As for userspace performance, an easy thing to try is to disable the RTP loop check by setting the macro RTP_LOOP_PROTECT to zero (either in call.h or through a Makefile setting).

**Comment by maxknax** [comment]
In the meantime, we found the problem and made some enhancements.
To give something back to the rtpengine community, here our changes:

/etc/sysctl.conf:
net.core.rmem_default = 31457280
net.core.rmem_max = 12582912
net.core.wmem_default = 31457280
net.core.wmem_max = 12582912
net.core.somaxconn = 65536
net.core.netdev_max_backlog = 65536
net.core.optmem_max = 25165824
net.ipv4.tcp_mem = 65536 131072 262144
net.ipv4.udp_mem = 65536 131072 262144
net.ipv4.tcp_rmem = 8192 87380 16777216
net.ipv4.udp_rmem_min = 16384
net.ipv4.tcp_wmem = 8192 65536 16777216
net.ipv4.udp_wmem_min = 16384

After that, we had Packet Loss because of hig ksoftirqd/0 load (with more than 3000 Calls).
Problem is, that in default configuration there is only one tx/rq queue in the network card configured. Because we are using SRIOV and this is a VM, we cant use the 64 Queues the NIC is supporting. There is a new Driver from Intel for the ixgbevf which supports 2 rx/tx queues. but first we tested the activation of RPS:

echo fffffff > /sys/class/net/eth0/queues/rx-0/rps_cpus
echo fffffff > /sys/class/net/eth1/queues/rx-0/rps_cpus

On both NICs.
And: 
Next day with more than 3000 concurrent calls: ksoftirqd/0 - 7 idling with 0.0 - 1.0 % CPU.
In the upcomming month the load will be back to 4000 - 5000 Calls and everything should be fine.

Interesting part is, that, before Update to Kamailio 4.2 and rtpengine (before was Kamailio 4.1 and mediaproxy-ng without Kernel mode) this type of configuration was not necessary.

**Comment by adubovikov** [comment]
Just for everybody who has a similar problem: don't forget to install "irqbalance", without the utility the network queues will not distributed across all CPU. (Debian 7, 8 ... and probablly for 9 as well)

**Comment by taurus-forever** [comment]
Just for the history, "irqbalance" is a part of default Sipwise NGCP installation since the Middle Ages:
```
+ngcp-nth (0.2.0) unstable; urgency=low
+  * Add "irqbalance" package to depends.
+ Fri, 29 Apr 2011 01:40:24 +0200
```
Anyway, tnx for sharing it here!

**Comment by adubovikov** [comment]
good for NGCP :-) Now is also good for another distributions :-)
