### ISSUE TITLE
Deleting tag for offered but not answered yet branch after deleting in another branch

### ISSUE THREAD

**Issue by vlitvinov** [sipwise/rtpengine#1315]
Hello. 

Let's me describe the call flow and explain the issue.
1) two offers with different branches (z9hG4bK393e.098e0fd91cd853622ffdd7bda2986347.0 and z9hG4bK393e.098e0fd91cd853622ffdd7bda2986347.1)
2) answer in branch z9hG4bK393e.098e0fd91cd853622ffdd7bda2986347.0
3) deleting in same branch (z9hG4bK393e.098e0fd91cd853622ffdd7bda2986347.0)
4) offer in new branch z9hG4bK193e.2ca57ba3a253e2e0c51bb7db8674d4c3.0
5) delete in branch (z9hG4bK393e.098e0fd91cd853622ffdd7bda2986347.1)
6) answer in last exist branch (z9hG4bK193e.2ca57ba3a253e2e0c51bb7db8674d4c3.0)
7) after conversation delete in this branch (z9hG4bK193e.2ca57ba3a253e2e0c51bb7db8674d4c3.0)

On step 4 "from-tag", "to-tag"  is the same as on step 1. On step 5 on deleting rtpe remove monologue with our from-tag (and probable removed from-tag from last branch). On the last step I receive an error "Tag 'as4074545e' in delete message not found, ignoring". 

I use DELETE_DELAY=0 

[rtpengine.log](https://github.com/sipwise/rtpengine/files/6846666/rtpengine.log)

**Comment by rfuchs** [comment]
I see that this is a modified rtpengine, so I'm not sure how I can support this.

The delete in your step 3 is done from the caller's POV (with `from-tag=xxx` and nothing else set), which should delete the entire call (both branches). So in your log you have this:

```
Jul 20 09:00:46 litvinov01 rtpengine[2107]: DEBUG: [63a877be2935cb447f0318da2050525f]: Dump for 'delete' from 127.0.0.1:55769: { "supports": [ "load limit" ], "call-id": "63a877be2935cb447f0318da2050525f", "received-from": [ "IP4", "85.238.100.162" ], "from-tag": "as4074545e", "command": "delete" }
Jul 20 09:00:46 litvinov01 rtpengine[2107]: INFO: [63a877be2935cb447f0318da2050525f]: Deleting call branch 'as4074545e' (via-branch '')
Jul 20 09:00:46 litvinov01 rtpengine[2107]: DEBUG: [63a877be2935cb447f0318da2050525f]: Destroying monologue 'as4074545e' ()
Jul 20 09:00:46 litvinov01 rtpengine[2107]: DEBUG: [63a877be2935cb447f0318da2050525f]: Destroying monologue '765975003' (z9hG4bK393e.098e0fd91cd853622ffdd7bda2986347.0)
Jul 20 09:00:46 litvinov01 rtpengine[2107]: INFO: [63a877be2935cb447f0318da2050525f]: Call branch 'as4074545e' (via-branch '') deleted
```

The last line should end with `no more branches remaining` and then followed by `Deleting entire call`. You didn't mention the version, so I tested this on 8.5, 9.5, and current master, and this is what happens. I can only guess that you don't get that because it's the code has been modified.

**Comment by vlitvinov** [comment]
Hello @rfuchs .
Thank you for feedback. You are right we use custom build based on 8.3.1 but with backported commit 8e22c9a41418932c17a1a971b01e51995285ffb2 (TT#85701 improve branch handling with delete-delay=0) that you did for us. 
You already fixed issue in first post by commit 87521ead3438b56b795d9836ae95f1709328caa4 (regression from 8e22c9a).

But I have another question. 
We tested with master and 8.3.1 from official git and got different behavior with branch logic. 
Should we use branch=extra flag in reInvite in case we use it before in this call?

Flow is the same as in the first post, but in step 4 we didn't set branch flag. 

In 8.3.1 on step 5 it delete only call branch.

[rtpengine_sipwise_8.3.1.log](https://github.com/sipwise/rtpengine/files/6861566/rtpengine_sipwise_8.3.1.log)
call id 7a3a2f6c36ea7af52b3fee7e5fbc9b61

In master (where is changes from TT#85701) on step 5 it delete call branch, all monologues and call.

[rtpengine_sipwise_master.log](https://github.com/sipwise/rtpengine/files/6861568/rtpengine_sipwise_master.log)
call id 7ed432971f31ecb075afcd1b32160428

**Comment by rfuchs** [comment]
So in this log I see: the offer from step 4 is using the same from/to tags as the answer in step 2. So from rtpengine's POV, this would be the same dialogue as was established in step 2, except that this dialogue has already been deleted in step 3. So I assume that rtpengine is now using the second branch (which hasn't been deleted) to fill in with that offer, which is probably not what you want.

The 8.3 branch isn't supported any more, which is why that commit you mentioned is missing from there. I would suggest to move to 8.5 at least.

**Comment by vlitvinov** [comment]
Thank you for your reply. 
We change the logic according to your comment.
