### ISSUE TITLE
Question: Performance with different kind of transcoding 

### ISSUE THREAD

**Issue by VidarHUN** [sipwise/rtpengine#1320]
Hello, 

In my setup, I want to test out which transcoding option will make the biggest CPU load at a certain number of calls. I mean the cost of transcoding a package from PCMU to PCMA will require the same amount of CPU that PCMU to Opus requires?

**Comment by rfuchs** [comment]
> I mean the cost of transcoding a package from PCMU to PCMA will require the same amount of CPU that PCMU to Opus requires?

No it most certainly will not. Transcoding always involves decoding the incoming codec to plain PCM (usually 16-bit or 32-bit), then possibly resampling the PCM to match the output sample rate, channels, and sample format, and then encoding the (resampled) PCM to the target codec.

So PCMU -> PMCA involves: decoding PCMU to 16-bit 8 Khz PCM, then encoding 16-bit 8 kHz PCM to PCMA.

while PCMU -> Opus involves: decoding PCMU to 16-bit PCM, resampling to 48 kHz because Opus always runs at 48 kHz, possibly upsampling to 2 channels and possibly changing the sample format if Opus requires it, and then encoding that 48 kHz PCM to Opus.

In general, the more sophisticated a codec is, the more CPU it will use for de/encoding. G.711 is trivial to de/encode, Opus not so much.

**Comment by VidarHUN** [comment]
I see, thank you for your satisfying answer!
