### ISSUE TITLE
Port preallocation

### ISSUE THREAD

**Issue by pengweichu** [sipwise/rtpengine#1332]
Hi, I would like to try rtpengine to replace our current RTP server.

Currently, our PBX is required to preallocate the port pool from RTP server, and uses preallocated ports to rewrite SDP, this will get good performance to process the calls. I would like to know does rtpengine supports this way?

Thanks.

**Comment by rfuchs** [comment]
What do you mean with "preallocate the port pool?"

**Comment by pengweichu** [comment]
> What do you mean with "preallocate the port pool?"

I mean allocate a bulk ports from rtp engine then cached in B2BUA pbx, once pbx received a call, get the port from cached ports to rewrite the SDP.

After read some doc, I think rtp engine doesn’t support this way, since the rtp engine need to rewrite the SDP.

**Comment by rfuchs** [comment]
I'm still not quite sure what you're asking for, but it does sound like that this is not supported by rtpengine. We do support the "TCP" and "UDP" control protocol (for example used by Kamailio's "rtpproxy" and "mediaproxy" modules) where rewriting the SDP is left up to the SIP proxy (or other controlling agent), but ports still need to be allocated during call establishment (and not before) since rtpengine needs to know where to forward RTP packets to, and that information isn't available before a call gets established.

**Comment by portsip** [comment]
> I'm still not quite sure what you're asking for, but it does sound like that this is not supported by rtpengine. We do support the "TCP" and "UDP" control protocol (for example used by Kamailio's "rtpproxy" and "mediaproxy" modules) where rewriting the SDP is left up to the SIP proxy (or other controlling agent), but ports still need to be allocated during call establishment (and not before) since rtpengine needs to know where to forward RTP packets to, and that information isn't available before a call gets established.

Thank you for your reply.
Our B2BUA PBX works in the following manner:

The caller sends an INVITE to the PBX.
When the PBX receives the INVITE, it sends an RPC call to the Media server to allocate a port. The Media server assigns a port and replies to the PBX with the port number, for example, 20000.
The PBX rewrites the SDP on port 20000, then sends a new INVITE to the callee, containing the SDP on port 20000 in the INVITE.

We don't want the thread blocked because we only use one thread to handle the call to avoid the mutex lock in our PBX, but when this thread sends RPC to the media server to get the port, it needs to
 wait for the response from the media server, causing our PBX to performance poorly.

In order to solve this issue, we use another thread (thread A) is responsible for maintaining a "ports pool" in the PBX. This thread monitored the ports pool size every 5-10 seconds, 
and if it was less than 100, it sent an RPC request to the media server asking for more ports to be allocated and cached to the "ports pool". When the PBX receives INVITE requests that the SDP be rewritten, all that is required is to obtain a port from the local "ports pool", there's no need to send an RPC to the media server and wait for a response.

Now I understand, the rtpengine can't adapt with our PBX.

**Comment by pengweichu** [comment]
> I'm still not quite sure what you're asking for, but it does sound like that this is not supported by rtpengine. We do support the "TCP" and "UDP" control protocol (for example used by Kamailio's "rtpproxy" and "mediaproxy" modules) where rewriting the SDP is left up to the SIP proxy (or other controlling agent), but ports still need to be allocated during call establishment (and not before) since rtpengine needs to know where to forward RTP packets to, and that information isn't available before a call gets established.

Thank you for your reply.
Our B2BUA PBX works in the following manner:

The caller sends an INVITE to the PBX.
When the PBX receives the INVITE, it sends an RPC call to the Media server to allocate a port. The Media server assigns a port and replies to the PBX with the port number, for example, 20000.
The PBX rewrites the SDP on port 20000, then sends a new INVITE to the callee, containing the SDP on port 20000 in the INVITE.

We don't want the thread blocked because we only use one thread to handle the call to avoid the mutex lock in our PBX, but when this thread sends RPC to the media server to get the port, it needs to
wait for the response from the media server, causing our PBX to performance poorly.

In order to solve this issue, we use another thread (thread A) is responsible for maintaining a "ports pool" in the PBX. This thread monitored the ports pool size every 5-10 seconds,
and if it was less than 100, it sent an RPC request to the media server asking for more ports to be allocated and cached to the "ports pool". When the PBX receives INVITE requests that the SDP be rewritten, all that is required is to obtain a port from the local "ports pool", there's no need to send an RPC to the media server and wait for a response.

Now I understand, the rtpengine can't adapt with our PBX.

**Comment by rfuchs** [comment]
So how does the media server then know where to forward RTP that it receives on one of these pre-allocated media ports?

FTR, rtpengine maintains this kind of port pool internally, and so the request to return a new port (and possibly rewrite the SDP) is processed very fast. Also this can be done asynchronously. There's no reason to block processing other calls while waiting for a response from rtpengine for one call. If the PBX does so anyway then that sounds like a poorly designed application.
