### ISSUE TITLE
Locking issue with graphite thread, when continue

### ISSUE THREAD

**Issue by smititelu** [sipwise/rtpengine#1345]
Hello,

We have found a locking issue with call_destroy() function, when redis DEL notification comes in.

More specifically, the issue happens at the **2'nd to last deleted call** (2'nd to last received DEL notification), and happens inside the
```
    for (int i = 0; i < NUM_CALL_ITERATORS; i++) { ...
```
and it either deadlocks at
```
    mutex_lock(&c->iterator[i].next_lock);
```
or it loops forever by entering
```
    if (prev_call) {
        if (mutex_trylock(&prev_call->iterator[i].next_lock)) { ...
```

I didn't found a fix, yet. Do you think of a possible fix for this?

Also, I saw this is a relatively new code so I want to ask why the need to lock prev and next call locks?

Thank you,
Stefan

**Comment by smititelu** [comment]
A fix for this can be: #1346 but will require not using the next/prev call locks. Let me know what you think.

**Comment by rfuchs** [comment]
The next and prev locks exists because this is a double linked list. So the "next" call's "prev" pointer points to "this" call and so must be locked in order to be changed. It wouldn't be safe removing an adjacent call from the list at the same time, and/or iterating the list at the same time without them. Or at least I think so... Yes this is new code and there have already been a few deadlock fixes in it, so it's quite possible there's still some bugs lurking. I'm open to suggestions. That being said, I don't quite understand the circumstances under which you would get a deadlock here.

**Comment by smititelu** [comment]
Hi,

Further debugging showed a deadlock between notification thread and graphite thread. Te actual problem is with graphite thread, add_ongoing_calls_dur_in_interval() function, when "continue" happens.

The "__next" pointer was not updated in ITERATE_CALL_LIST_START define due to "continue", causing mutex_lock on the "next_lock" of the same call.

Updated PR #1346 with the fix. Let me know what you think.

Thank you,
Stefan

**Comment by rfuchs** [comment]
Thanks, this seems to make a lot more sense. In fact I would rather disallow usage of `continue` within a call iterator altogether, and instead replace it with a `goto next` (pointing to just before the `ITERATE_CALL_LIST_NEXT_END`) for a much simpler patch. Either that, or restructure the code into an `if/else` instead of the `continue`. Is this something you could test?

**Comment by smititelu** [comment]
Hi,

I've updated the PR with ```goto next``` fix. Tested it and issue is not happening anymore.

Thank you,
Stefan
