### ISSUE TITLE
No audio and video after reinvite with video in sdp

### ISSUE THREAD

**Issue by akam-it** [sipwise/rtpengine#1366]
Hello, I have found strange behavior, that I, unfortunately, can not explain. I think it may be a bug.

I have asterisk. I have kamailio and rtpengine on the same host under NAT, and webrtc client.
```interface=internal/10.10.55.6;external/10.10.55.6!KAMAILIO_PUBLIC_IP```

When I call from a local network to a webrtc client, INVITE (to a webrtc client leg) have such ICE candidates in SDP:
**INVITE**
```
v=0
o=- 1518847960 1518847960 IN IP4 KAMAILIO_PUBLIC_IP
s=Asterisk
c=IN IP4 KAMAILIO_PUBLIC_IP
t=0 0
m=audio 12058 RTP/SAVPF 8 101
a=maxptime:150
a=mid:1
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:12059
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-256 72:7D:A5:1B:67:59:DD:C2:DE:46:EC:8D:12:3B:F5:85:ED:3B:38:5F:E5:6C:5D:3D:F0:AC:B9:A2:2F:13:C8:07
a=ptime:20
a=ice-ufrag:0Y6EWFAE
a=ice-pwd:nzcRKeVABLIemfgO9IslUmgBUL
a=candidate:HE5F45gvMh9sS6HG 1 UDP 2130706431 KAMAILIO_PUBLIC_IP 12058 typ host
a=candidate:HE5F45gvMh9sS6HG 2 UDP 2130706430 KAMAILIO_PUBLIC_IP 12059 typ host
```

**200OK from webrtc client:**
```
v=0
o=- 2888723958576192502 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC
m=audio 9 RTP/SAVPF 8 101
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:3056449384 1 udp 2113937151 2a800c1f-beb4-4643-8b18-3c2fad0edde9.local 40279 typ host generation 0 network-cost 999
a=ice-ufrag:ih54
a=ice-pwd:ko1QLqnq0IKTzo2ifrkiDejl
a=ice-options:trickle
a=fingerprint:sha-256 77:43:63:56:9C:EB:D0:EF:D9:1F:0C:90:3A:36:8D:67:C5:A3:CA:CF:F4:DF:5A:3F:CF:7E:C9:7B:C2:2F:12:38
a=setup:active
a=mid:1
a=sendrecv
a=msid:DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC 1965697d-39c4-44a5-b0e1-fa399f3a62e6
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ssrc:1290316227 cname:6DlNeWVetMmenQHv
a=ssrc:1290316227 msid:DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC 1965697d-39c4-44a5-b0e1-fa399f3a62e6
a=ssrc:1290316227 mslabel:DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC
a=ssrc:1290316227 label:1965697d-39c4-44a5-b0e1-fa399f3a62e6

```

All works fine, just audio, no video yet. After this I am enabling video on my local client, and I can see this in reINVITE to a webrtc client (notice local ice candidates in video part):

**reINVITE**
```
v=0
o=- 1518847960 1518847961 IN IP4 KAMAILIO_PUBLIC_IP
s=Asterisk
c=IN IP4 KAMAILIO_PUBLIC_IP
t=0 0
m=audio 12058 RTP/SAVPF 8 101
a=maxptime:150
a=mid:1
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv
a=rtcp:12059
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-256 72:7D:A5:1B:67:59:DD:C2:DE:46:EC:8D:12:3B:F5:85:ED:3B:38:5F:E5:6C:5D:3D:F0:AC:B9:A2:2F:13:C8:07
a=ptime:20
a=ice-ufrag:0Y6EWFAE
a=ice-pwd:nzcRKeVABLIemfgO9IslUmgBUL
a=ice-options:trickle
a=candidate:HE5F45gvMh9sS6HG 1 UDP 2130706431 KAMAILIO_PUBLIC_IP 12058 typ host
a=candidate:HE5F45gvMh9sS6HG 2 UDP 2130706430 KAMAILIO_PUBLIC_IP 12059 typ host
a=remote-candidates:1 WEBRTC_CLIENT_PUBLIC_IP 40279
a=end-of-candidates
m=video 12104 RTP/SAVPF 99
a=mid:2
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42E01F
a=sendrecv
a=rtcp:12105
a=rtcp-mux
a=setup:actpass
a=fingerprint:sha-256 72:7D:A5:1B:67:59:DD:C2:DE:46:EC:8D:12:3B:F5:85:ED:3B:38:5F:E5:6C:5D:3D:F0:AC:B9:A2:2F:13:C8:07
a=ice-ufrag:Gp236Y8f
a=ice-pwd:f9BCNYvm8MIIt4Jhhlhxn7e5Pp
a=candidate:cY3EYmRxKVDuBoSH 1 UDP 2130706431 10.10.55.6 12104 typ host
a=candidate:cY3EYmRxKVDuBoSH 2 UDP 2130706430 10.10.55.6 12105 typ host
```

**and 200OK from webrtc client:**
```
v=0
o=- 2888723958576192502 3 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC
m=audio 9 RTP/SAVPF 8 101
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:3056449384 1 udp 2113937151 2a800c1f-beb4-4643-8b18-3c2fad0edde9.local 40279 typ host generation 0 network-cost 999
a=ice-ufrag:ih54
a=ice-pwd:ko1QLqnq0IKTzo2ifrkiDejl
a=ice-options:trickle
a=fingerprint:sha-256 77:43:63:56:9C:EB:D0:EF:D9:1F:0C:90:3A:36:8D:67:C5:A3:CA:CF:F4:DF:5A:3F:CF:7E:C9:7B:C2:2F:12:38
a=setup:active
a=mid:1
a=sendrecv
a=msid:DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC 1965697d-39c4-44a5-b0e1-fa399f3a62e6
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ssrc:1290316227 cname:6DlNeWVetMmenQHv
a=ssrc:1290316227 msid:DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC 1965697d-39c4-44a5-b0e1-fa399f3a62e6
a=ssrc:1290316227 mslabel:DIhD0mJSRxwMbH32IYPrOgTrmUqOq8L8qiSC
a=ssrc:1290316227 label:1965697d-39c4-44a5-b0e1-fa399f3a62e6
m=video 48912 RTP/SAVPF 99
c=IN IP4 WEBRTC_CLIENT_PUBLIC_IP
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:3056449384 1 udp 2113937151 2a800c1f-beb4-4643-8b18-3c2fad0edde9.local 48912 typ host generation 0 network-cost 999
a=candidate:842163049 1 udp 1677729535 WEBRTC_CLIENT_PUBLIC_IP 48912 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999
a=ice-ufrag:yBdv
a=ice-pwd:Gtlt/+mgNzyXwSe3xDMxHeRH
a=ice-options:trickle
a=fingerprint:sha-256 77:43:63:56:9C:EB:D0:EF:D9:1F:0C:90:3A:36:8D:67:C5:A3:CA:CF:F4:DF:5A:3F:CF:7E:C9:7B:C2:2F:12:38
a=setup:active
a=mid:2
a=recvonly
a=rtcp-mux
a=rtpmap:99 H264/90000
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

```

- after this reINVITE there is no video and even no audio on the webrtc client.
- if my local client call with video in the begining (without reinvites) to the webrtc client all also works fine, and there are KAMAILIO_PUBLIC_IP in the video ice candidates
- if webrtc client connected to VPN and have route to 10.10.55.6 all works fine

Version: 10.0.1.4+0~mr10.0.1.4 but was tested on latest 9x and 8x also

rtpengine logs https://pastebin.com/V9xD8ZGc

**Comment by akam-it** [comment]
kamailio private ip: 10.10.55.210
kamailio private ip: 10.10.55.6 (virtual ip by keepalived on the same network interface)
kamailio public ip: KAMAILIO_PUBLIC_IP (natted to 10.10.55.6)
asterisk ip: 10.10.55.7
10.101.14.7 - my local client, android softphone with video support
WEBRTC_CLIENT_PUBLIC_IP - my webrtc client's public IP. desktop with webrtc client have not route to kamailio network by default (but if connected all works)

**Comment by rfuchs** [comment]
Looks like some kind of ICE problem. In the original answer, the WebRTC client is only sending a `.local` host name as ICE candidate address, so rtpengine has no way to directly resolve this and run checks against it. It eventually starts working because the WebRTC client is running a check against rtpengine, and so rtpengine learns the remote endpoint from that check, and ICE converges on that one candidate pair. (If the WebRTC client is sending more candidates through trickle ICE, you need to pass these to rtpengine separately, e.g. by handling SIP INFO.)

In the re-invite answer, the WebRTC sends the same candidate for the audio section, so this should continue to work. (Although the WebRTC client is misbehaving here, as the `c=` address and `m=` port is now supposed to reflect the ICE candidate in use, and not the trickle ICE address.) For the video section, the client sends one candidate which looks similar to the audio one (with a host name, so not usable), plus one with a usable address. (Some misbehaviour here again, as the RTP address and port here are given explicitly, and not the trickle ICE address, but the RTCP address somehow is still given as the trickle ICE address.) So now rtpengine can run checks against that one usable ICE candidate, but is apparently not receiving any replies. It's also not receiving any incoming checks from the WebRTC client as it did on the audio media before, which leaves no usable ICE candidate. I see no reason for audio stop working here, so I suspect a problem in the WebRTC client.

**Comment by akam-it** [comment]
why rtpengine send his private ip address in reINVITE, instead of sending his public one?

**Comment by akam-it** [comment]
and these 200ok in my issue are from tryit.jssip.net webrtc client (downloaded), to be sure that the reason is not my webrtc client, because my webrtc client has the same behavior.

I will try to use online version of tryit.jssip.net client to check this issue.

**Comment by rfuchs** [comment]
> why rtpengine send his private ip address for video in reINVITE, instead of sending his public one?

Because you're omitting the `direction` flag in the re-invite. Interfaces are associated with individual media sections, so when a new media section is added, the interface must be explicitly given, or else the default will be chosen.

> is it ok?

I don't know? Depends on what your network looks like and where the clients are sitting.

**Comment by akam-it** [comment]
Thank you for your answers and sorry for disturb, the problem was in my kamailio config, now it sends public IP in candidates in reINVITE, and now audio and video are working.
I was confused that in reINVITE was public IP in audio candidates and private IP in video candidates. Because of this, I thought that problem is not in my config files.
