### ISSUE TITLE
SIP "HOLD" fails due to ICE restart

### ISSUE THREAD

**Issue by robdyck** [sipwise/rtpengine#1411]

**Comment by robdyck** [comment]
Shouldn't have hit the tab key - sorry
version git-master-830abd67
I am experiencing a problem with WEBRTC interworking with very basic phones that don't support ICE. ICE is mandatory when working with WEBRTC. I can use ICE=force or ICE=optional to setup the call. The trouble arises when the WEBRTC UA goes on hold. Firefox is very clear about why it drops the call. "Remote description indicates ICE restart but offer did not request ICE restart". ICE restart means change the ICE tags ( ufrag and pwd). My understanding of ICE restart is to accomodate things like momentary interuption or hand off to another network.

Is there a way to configure this differently? Does this require a feature request to remember the ICE tags while in dialog?

**Comment by rfuchs** [comment]
ICE restart is implicit and required when certain attributes in the SDP change. This shouldn't happen unless there's something wrong in your signalling.

Since this is not a code issue, take this to the mailing list: https://rtpengine.com/mailing-list

Start by posting some logs so we can see what's going on, ideally full debug logs from rtpengine.
