### ISSUE TITLE
Module xt_RTPENGINE not found

### ISSUE THREAD

**Issue by Pavelt132** [sipwise/rtpengine#1573]
After installing and first starting the rdpengine latest version, I get the error:

ngcp-rtpengine-iptables-setup[990]: modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/5.10.0-18-amd64

root@webrtc:/lib/modules/5.10.0-18-amd64# ls
kernel         modules.alias.bin  modules.builtin.alias.bin  modules.builtin.modinfo  modules.dep.bin  modules.order    modules.symbols
modules.alias  modules.builtin    modules.builtin.bin        modules.dep              modules.devname  modules.softdep  modules.symbols.bin

  Operating System: Debian GNU/Linux 11 (bullseye)
  Kernel: Linux 5.10.0-18-amd64
  Architecture: x86-64

**Comment by rfuchs** [comment]
As this is almost certainly not an issue with the code, please use the mailing list for questions like this.

Your running kernel probably doesn't match the version of the kernel headers that are installed.

If using Debian packages, run `dpkg-reconfigure rtpengine-kernel-dkms` and see what you get. You can also check the status with `dkms status`. Then you can trigger a rebuild with `dkms build ...`

**Comment by BaldingVoIP-engineer** [comment]
@Pavelt132 - I had this previously in an AWS environment (I was using Debian buster though)

I had to update Linux headers AFTER the install (so where you are at now hopefully) then reboot and it associated automatically for me. 

You can check once up again using modprobe command - if its blank it should be good, otherwise it will return an error.

**Comment by Pavelt132** [comment]
thank you! The problem is solved
1) sudo apt install linux-headers-$(uname -r)
2) reboot
