### ISSUE TITLE
pong packets of rtpengine  cannot arrive sip-proxy

### ISSUE THREAD

**Issue by helios741** [sipwise/rtpengine#1584]
The network topology is as follows:
![image](https://user-images.githubusercontent.com/12036324/209948208-8fe3a494-ff02-4834-9ba4-43f8595e9d3e.png)

1. rtpengine machine has two network card
2. eth0 has a private ip(out), and eth1 have a public ip(in)
3. rtpengine listen  public ip(eth1)
4. not firewall rules
when i start sip proxy, i can get follow error messages:
```code
 1(10) ERROR: rtpengine [rtpengine.c:2902]: send_rtpp_command(): timeout waiting reply for command "ping" from RTPEngine <udp:39.105.37.100:22222>
 1(10) ERROR: rtpengine [rtpengine.c:2771]: rtpp_test(): proxy did not respond to ping
 1(10) ERROR: rtpengine [rtpengine.c:2902]: send_rtpp_command(): timeout waiting reply for command "ping" from RTPEngine <udp:39.107.67.48:22222>
 1(10) ERROR: rtpengine [rtpengine.c:2771]: rtpp_test(): proxy did not respond to ping
```
then I captured packets through tcpdump:
machine of sip-proxy only out package but don't get back packet:
![image](https://user-images.githubusercontent.com/12036324/209948082-2916001d-1c2c-4175-8c76-a8ce7cc83f37.png)

machine of rtpengine:
![image](https://user-images.githubusercontent.com/12036324/209947864-c60ee63a-8ea5-44c3-b17f-e110e1aaf254.png)

I looked at the document and didn't see anything about it, may I ask what causes this?

**Comment by rfuchs** [comment]
Probably because of the asymmetric network path between the ping and the pong. Source and destination addresses should match for both directions, and I believe received packets with mismatched addresses are discarded for `connect`ed UDP sockets.

This is a code issue tracker, not a general support forum, especially not for problems related to your network setup. Use the mailing list instead.
