### ISSUE TITLE
support for kqueue

### ISSUE THREAD

**Issue by cahlbin** [sipwise/rtpengine#173]
Would you be interested in adding support for kqueue? I have done some experiments in getting rtpengine to run on Mac OS X (for development mode only) and have added some basic support for kqueue, see https://github.com/cahlbin/rtpengine/commit/92d202896da449e0b451e176a89518ff4e6630f8 

If you are interested in having the feature merged, would you prefer a separate poller_kqueue.c (as the commit above), or would you want it integrated into the existing poller.c. If the latter, any particular preferences and/or recommendations on use of inline pre-processor defined conditionals? Then I could go ahead and fix up the commit for a PR.

**Comment by rfuchs** [comment]
Sure, why not. A separate file for it sounds like a good idea, but I would want to avoid code duplication as much as possible. I would prefer a generic poller.c and then poller_epoll.c and poller_kqueue.c (or w/e) containing only the code specific to each mechanism. Kinda like a layer of abstraction. If that's feasible to do at all. Otherwise I think I'd prefer preprocessor instructions.

**Comment by rfuchs** [comment]
Cleaning up old tickets
