### ISSUE TITLE
rtpengine matrcses 

### ISSUE THREAD

**Issue by sasmita11** [sipwise/rtpengine#1745]
Hi , 

this is not an issue . I just wanted to know about the rtpengine matrces which I can see on prometheus . 

Is there any detailed documentation for this ?

**Comment by rfuchs** [comment]
If it's not an issue, then why open an issue? We have a mailing list for general questions.

The docs are provided in-line, although not all of them translate fully due to the use of Prometheus labels.

```
$ curl http://localhost:8000/metrics
# HELP rtpengine_sessions Owned sessions
# TYPE rtpengine_sessions gauge
rtpengine_sessions{type="own"} 0
rtpengine_sessions{type="foreign"} 0
# HELP rtpengine_transcoded_media Transcoded media
# TYPE rtpengine_transcoded_media gauge
rtpengine_transcoded_media 0
# HELP rtpengine_mediastreams Userspace-only media streams
# TYPE rtpengine_mediastreams gauge
rtpengine_mediastreams{type="userspace"} 0
rtpengine_mediastreams{type="kernel"} 0
rtpengine_mediastreams{type="mixed"} 0
# HELP rtpengine_uptime_seconds Uptime of rtpengine
# TYPE rtpengine_uptime_seconds gauge
rtpengine_uptime_seconds 8
# HELP rtpengine_sessions_total Total managed sessions
# TYPE rtpengine_sessions_total counter
rtpengine_sessions_total 0
...
```

The metrics generally mirror the stats provided through other channels (e.g. `rtpengine-ctl list totals`) so it should be straight forward to figure out what is what.
