### ISSUE TITLE
rtpengine complains about missing /var/spool/rtpengine

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#272]
I built 4.5.1 and it complains about missing  /var/spool/rtpengine at start:

Sep 11 18:19:54 lohi rtpengine-daemon[28714]: Starting RTP/media proxy: rtpengine-daemonSpool directory "/var/spool/rtpengine" does not exist.
Sep 11 18:19:54 lohi rtpengine-daemon[28714]: Error while setting up spool directory "/var/spool/rtpengine".

In my opinion missing  /var/spool/rtpengine should not be reported as an error.  Instead it means that recording function is not in use.  Alternatively, var/spool/rtpengine should be added to debian/dirs.

-- Juha

**Comment by rfuchs** [comment]
I would suggest that an empty/unspecified `--recording-dir` counts as recording not desired nor supported and thus the spool should be left untouched. Right now, recording-dir unspecified would make it default to `/var/spool/rtpengine`. What do you think @dbmikus  ?

**Comment by dbmikus** [comment]
If we allow the user to run rtpengine without creating a spool directory, then we will run into issues if they send an offer/answer message with "record-call". There will be no place for those output files to go. It would be possible to dump them in `/tmp` somewhere, or perhaps create a folder in `/tmp`, as the user is more likely to have write permissions for that directory. That doesn't seem to be as appropriate a place, but then I don't think we'll run into these unexpected errors.

So, let me just itemize the ideas I have off the top of my head:

1. Add `/var/spool/rtpengine` to `debian/dirs` and keep `/var/spool/rtpengine` as the default spool directory. This is the most logical place for the directory, in my opinion, but this might be considered unnecessary folder clutter. The user might also run into permission issues.
2. Put the folder in `/tmp/rtpengine` by default. Everybody should be able to write to `/tmp`, so this seems like a clean default. If the user wants a different place, they'll have to manually do that and ensure its permissions. This could cause unintended confusion for the user if `/tmp` is a temporary directory.
3. Make compilation of recording support optional. I don't like this option, but it gets rid of the spool directory problem when users don't want it. If they compile it in, we still need one of the above. Additionally, if spool becomes used for something besides recording, this part would need to be refactored.

I'd vote for option 1. I think `/var/spool/rtpengine` should have "rwx" for all users, with sticky bit set (so users can't tamper with what rtpengine fills in), and then rtpengine can write files/directories to `/var/spool/rtpengine` with the permissions and user that rtpengine runs as. Does these permissions make sense?

Tagging @egreenmachine and @etamme, since they worked on this, too.

**Comment by rfuchs** [comment]
I would still like to support using rtpengine without forcing presence of a spool directory. If no call recording is desired and none is ever requested, it makes no sense to insist on a spool directory. If call recording is ever requested and no spool directory was specified, the call would simply be rejected with an error.

**Comment by etamme** [comment]
Yeah i think we can basically set some "global" on startup that indicates support for recording is enabled because a spool directory has been specified.  If that "global" is not set to true and we get a request with flags record-call=true we simply return an error to the offer/answer request.

**Comment by rfuchs** [comment]
Possible fix referenced above

**Comment by etamme** [comment]
That commit looks good to me @egreenmachine any other comments/thoughts?
