### ISSUE TITLE
rtpengine-ctl stops returning / printing any data

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#280]
We've started running rtpengine with a bit more load (only 50 or sessions) and one of our relays has stopped printing any results when using rtpengine-ctl.

```
$rtpengine-ctl list numsessions
$

```

The logs show the command is being received ...

```
2016-10-11T16:45:50.441932+00:00 media-relay2-0 rtpengine[8263]: INFO: New cli connection from 127.0.0.1:36436
2016-10-11T16:45:50.441941+00:00 media-relay2-0 rtpengine[8263]: INFO: Got CLI command:list numsessions
```

It just doesn't print any thing.  I've tried various commands.  I had been running various list numsessions commands throughout the morning and it was all working fine.  The box is still processing traffic, and relaying rtp without issue.  Is there any way to ... "reset" the cli without having to restart rtpengine, or do you have any other suggestions?

Thank you.

**Comment by rfuchs** [comment]
Tagging @smititelu  @inf265 and @lbalaceanu as this is their code

**Comment by pkuzak** [comment]
O.K., this is new to me. We're using this command quite often and we've never encountered this issue. What we've encountered in the past is that _rtpengine-ctl_ somehow started to "hang", and did not return. Back then we didn't find the route cause of this problem and because it happened very seldom we didn't investigate very much. Instead, we've committed https://github.com/sipwise/rtpengine/commit/25bbf036015a103f8b827f8b4bf9d3fbbcb7c7ca . I assume when you issue the _rtpengine-ctl_ command it is returning after 3s, right? Since that commit, we've never run into the issue again. 
A restart of the _rtpengine_ process solves the problem. Yet, I don't know about a way to "reset" the _cli_ without restarting _rtpengine_, but we will take a look at this issue and report back here when we've found something (or not).  
In the meantime we'll be grateful for any information you can provide to us which you think might help for debugging.

**Comment by etamme** [comment]
Thanks for the responses.  

Yes, we have been getting returns after 3 seconds, but its just not printing anything.

To give you more info - we have parallel forking setup, so some branches get an offer that is never answered, so we have sessions where one side of the monolog null.  To filter these out I wrote a little called [list_sessions.sh](https://gist.github.com/etamme/bf4cd79058697f70c1b76c6ef7e51f53) and have been running

`watch ./list_sessions.sh`

This has been working fine up until one of the 4 rtpengines we are running stopped returning any data.  I then started trying to use the raw

`rtpengine-ctl list numsessions`  

as well as other commands, all returned after 3 seconds, but none printed any data.  

I dont know if the default watch interval of 2 seconds was maybe causing problems?  Either way, I will change it to watch -n3 and see if the issue happens again.  If it does I will certainly update this issue.  

Is there any other type of "debugging" information I could supply to help diagnose the issue should it happen again?

**Comment by pkuzak** [comment]
Thanks for you input. Right now I don't know if there are other debugging information you could provide, but what you've provided already is quite helpful, because we also ran into that issue by using a _watch_ command (think our interval was 1s). So this is kind of a hint. 
Back then we used the _watch_ command mainly for the same reason you probably do, to get some sort of statistics. We stopped using it after we've implemented statistic support using [Graphite](https://graphiteapp.org/). Among other values, _rtpengine_ will also report values like _nopacket_relayed_sess_ and _oneway_stream_sess_, maybe this is what you need and you want to try it out. If so, it's just setting the GRAPHITE and GRAPHITE_INTERVAL variables in the configuration file to appropriate values. (You don't have to setup a Graphite server in the first place, e.g. you can just write a simple script waiting for the TCP connection and parse the incoming messages by yourself).
Nonetheless we will have a look on the _rtpengine-ctl_ command, as it should not block even if called repetitively.

**Comment by etamme** [comment]
I changed my watch to watch -n 10, and I am not getting no printed results on two of our relays.

**Comment by pkuzak** [comment]
Maybe this can be closed? At least I can't reproduce it. I just ran ```watch -n1 "rtpengine-ctl list numsessions"``` for several hours on several machines with each having a load >100 session without running into this issue. I used the master branch.

**Comment by etamme** [comment]
Yeah I don't think we are experiencing this issue any more either.
