### ISSUE TITLE
Send RTCP for endpoints that cannot

### ISSUE THREAD

**Issue by egreenmachine** [sipwise/rtpengine#312]
We would like to use rtpengine to send RTCP for endpoints that cannot send RTCP. This would be especially useful in the case of a WebRTC client calling a legacy SIP client. WebRTC requires RTCP for video to flow correctly, and there are many endpoints that do not support any RTCP. We are already in the middle of these media streams handling the DTLS decryption and ICE negotiation, so injecting the necessary RTCP packets into the stream should not be too difficult. Ideally we would be able to track the stream and report proper statistics back to the client. The big downside here is that it would only be RTCP for half of stream, but I feel this is better than no RTCP at all.

I can probably start writing some of this into the rtpengine daemon. I am curious to get your thoughts on this. It looks like there is already some code to detect RTCP packets on the stream.

**Comment by rfuchs** [comment]
This feature is on my own wishlist (to-do list) as well. Generating and sending RTCP packets isn't a big deal per se, but there's a few caveats.

* RTCP packets are sequence numbered in an encrypted context, so if packets are generated and injected, packets forwarded from the other media leg must either be blocked or renumbered accordingly.
* Not all stats required to generate every kind of RTCP packet are currently available. If things like jitter ought to be reported, measurement of these stats must be implemented.
* Most important for WebRTC are the RTCP feedback packets. It might be sufficient to generate these types and forward all others transparently as before. My expertise with RTCP FB packets is limited, but my understanding is that they rely on events and stats encountered during decoding of the (video) media, which implies that the media must be decoded to properly generate RTCP FB packets. Since rtpengine doesn't do this currently, this is why it also currently doesn't support sending RTCP FB packets. This one might be a deal breaker unless it's feasible to send these packets without getting into video codecs.
* Compound RTCP packets do exist and in some cases are required.

**Comment by rfuchs** [comment]
Cleaning up old tickets
