### ISSUE TITLE
incoming calls with no audio after 5 secunds

### ISSUE THREAD

**Issue by janfuri** [sipwise/rtpengine#351]
Hello,
I think this is not an issue of rtpengine but I haven't found any better contact for support.

I am facing a following audio issue.
When an incoming call is made, rtp media session is established and then after +-5 seconds audio is muted.

I think that problem is when RTCP tries to be established.
On server where RTPENGINE runs I have a firewall that DROPs OUTPUT packets to PRIVATE IP ADDRESSES. When I disable dropping output packets audio works well.

Attached full debug7 log: 
[rtpengine.txt](https://github.com/sipwise/rtpengine/files/943678/rtpengine.txt)

Thanks for your help,
Jan

**Comment by rfuchs** [comment]
According to the log, the RTP packets are actually received from a private IP address (`Confirmed peer address as 192.168.7.3:23217`). So the host running rtpengine can obviously communicate with these addresses. Why do you have a firewall rule disallowing this?

**Comment by janfuri** [comment]
OK, in the firewall is an exception for 192.168.7.0/24 network, that's why rtpengine can communicate.
And we need to have these rules in FW because of some internal reasons.

**Comment by rfuchs** [comment]
I see, so it's erroring when trying to send to 192.168.28.102? Which is actually an IP behind NAT I suppose?

Unfortunately I don't have a good quick solution for this. A send error is treated as fatal for the entire call. Workarounds I can find online suggest to use a null/dummy route instead of a DROP iptables rule.

You can manually patch it to make send errors non-fatal like this: https://gist.github.com/rfuchs/7a6aa8ac0bf4389097efc32d3a97a65b

**Comment by janfuri** [comment]
Thank you for your help
