### ISSUE TITLE
Issue in rtp installation (dpkg-buildpackage)

### ISSUE THREAD

**Issue by kkbansal** [sipwise/rtpengine#365]
root@ozonetelwbrtc2:/usr/src/rtpengine# dpkg-buildpackage
dpkg-buildpackage: source package ngcp-rtpengine
dpkg-buildpackage: source version 5.3.0.0+0~mr5.3.0.0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Sipwise Jenkins Builder <jenkins@sipwise.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build rtpengine
dpkg-source: info: using options from rtpengine/debian/source/options: --extend-diff-ignore=.gitreview
dpkg-checkbuilddeps: Unmet build dependencies: libavcodec-dev (>= 6:10) libavfilter-dev (>= 6:10) libavformat-dev (>= 6:10) libavresample-dev (>= 6:10) libavutil-dev (>= 6:10)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by mika** [comment]
Install `libavcodec-dev (>= 6:10) libavfilter-dev (>= 6:10) libavformat-dev (>= 6:10) libavresample-dev (>= 6:10) libavutil-dev (>= 6:10)` as being told in the error message?

**Comment by kkbansal** [comment]
but how i install  libavcodec-dev ( >=6:10 ) ?
when i use "apt-get install libavcodec-dev" it's install 6:9 version

**Comment by mika** [comment]
What distribution are you using? 

Because for Debian there's  6:0.8.17-2 in wheezy and 6:10.1-1~bpo70+1 in wheezy-backports, 6:11.9-1~deb8u1 in jessie and 7:3.2.4-1~bpo8+1 in jessie-backports.
6:9 sounds like Ubuntu 14.04 LTS with its 6:9.11-2ubuntu2 from trusty/universe?

You need to either compile/build/install on your own or find something like a PPA providing the according package(s) for trusty.

**Comment by rfuchs** [comment]
Closing this as we don't support older distros.
