### ISSUE TITLE
UnHold problem

### ISSUE THREAD

**Issue by falconsapsan** [sipwise/rtpengine#393]
JsSIP v3.0.15 * JsSIP v3.0.15
rtpengine version: 5.5.0.0+0~mr5.5.0.0

JsSIP -> Opensips (rtpengine) -> Freeswitch

# For Chrome, Opera
user A --> calling -->user B  (all OK)
user A --> hold  --> user B (all OK, user B hear hold music)
user A --> unhold -->user B  (user B does not hear user A)

# For Firefox
user A --> calling -->user B  (all OK)
user A --> hold  --> user B (all OK, user B hear hold music)
user A --> unhold -->user B  (user A does not hear user B)

This is  bug?

**Comment by rfuchs** [comment]
You'd have to a post a full debug log (log level 7) to find out

**Comment by egreenmachine** [comment]
I've tested renegotiation with the [SIP.js renegotiation branch](https://github.com/onsip/SIP.js/pull/426) and rtpengine. Rtpengine works flawlessly in the cases outlined above and more. I would be surprised if JsSIP were doing something different enough that would be causing rtpengine to be the problem. Specifically because the SDP is generated from the browser itself, not the library.

**Comment by IvanKalashnikov** [comment]
Hello, get same problem, but use kamailio + freeswitch + rtpengine + jssip
Rtpengine Version: 7.4.0.0+0~mr7.4.0.0 git-master-285773f
Attach log with loglevel 7
[unhold.log](https://github.com/sipwise/rtpengine/files/3325742/unhold.log)

**Comment by rfuchs** [comment]
@IvanKalashnikov the log doesn't show anything that would explain loss of audio. Please check on the sides of the RTP clients.

**Comment by rfuchs** [comment]
Cleaning up old tickets
