### ISSUE TITLE
Random audio loss after browsers update

### ISSUE THREAD

**Issue by caruizdiaz** [sipwise/rtpengine#46]
After FF (33.1.1) and Chrome (39.0.2171.71) updates, rtpengine behaves erratically in the sense of audio flow establishment. Sometimes, it works, sometimes, it doesn't.

I originally identified this behavior after Chrome mobile update, to 39.0.2171.59, and I thought it was a bug with the browser since it didn't happen with the desktop version which remained v38 until a couple of days ago. After this event, the two major browsers I mentioned, started to show this symptom. 

Another interesting thing is that the problem appears only with browser to browser calls. With browser to softphone (csipsimple) it works properly.

I rolled rtpengine back to commit "19e02817447d430c596208e1a3cb3a0acb79b413", and everything went back to normal. I believe some of the changes with the DTLS management introduced some kind of bug.

Regards,
Carlos

**Comment by vance-od** [comment]
Hi Richard, Carlos! 
I wonder what was the cause of the discussed issue, cos it is closed, and I do not completely understand how it has finished.

I'm asking, because currently have similar issue with chrome on android 
(not to open new thread, I'll ask here, it seems not rtpengine problem, but I would appreciate any idea what could be wrong, as well I'm preparing bug request to chromium list now):

Setup:
UA-A sipjs based client running on chrome mobile (M48stable/M49dev) - 10.100.7.101 
UA-B - sip phone
sip server - kamailio+rtpengine+asterisk - 10.100.1.85

Call script:
UA-A call UA-B
media exchange succesful, in some random moment of time both-way audio stops

in rtpengine log (debug 7) I see, that after log "Processing incoming DTLS packet", ICE stop working, media stops as well. The complete log here: https://gist.github.com/vance-od/a8539a03122f925dd550

In Chrome (chrome://webrtc-internals), when problem occurred I see (seems as Chrome for some reasons closed connection):
- stop
- IceConnectionStateChanged -> IceConnectionStateClosed
- signallingStateChanged -> SignalingStateClosed

The dump for the call [here](https://www.dropbox.com/sh/0yp94wa03hffwag/AABtrfutZ65iNd1ijDKp4__la?dl=0) (done on the server's side) (there are only related packets, complete dump could be sent privately)
in trace I see everything is as common till receiving from Chrome "DTLSv1.0 Encrypted Alert"

When problem appear, there is no changes in signalling.

Any idea, with such issue?

**Comment by rfuchs** [comment]
"Encrypted alert" is a TLS message usually used to signal the closing of the connection. So this is expected when Chrome closes the connection. There's nothing in the log or the dump that would explain why it would do that.

**Comment by vance-od** [comment]
as turned out, the problem is in  android device, after screen off it stops media after 1 minute
It's a known issue under discussion, https://code.google.com/p/chromium/issues/detail?id=513633.
