### ISSUE TITLE
rtcp rr handling in ssrc_receiver_report 

### ISSUE THREAD

**Issue by jerzyptak** [sipwise/rtpengine#476]
The logic of determining payload type pt in ssrc_receiver_report function is inconsistent. When __calc_rtt provides the value, then pt is based on the rr->ssrc (I think that is correct), but when __calc_rtt  does not provide the value for pt, then pt is based on rr->from (that is a stream in the opposite direction). That can not be correct?

**Comment by rfuchs** [comment]
It used to be a workable fallback, but with transcoding, the assumption that the payloads match on both sides doesn't hold any more. Thanks for noticing.

**Comment by jerzyptak** [comment]
I would think that when the media packets are handled in the kernel, then trying to associate correct payload type and ssrc is almost impossible - they can change at any time (codec can be changed to a different one advertised in sdp and ssrc also can change - I am also testing endpoints that will send rtp keep alive packets with pt = 88 and with a new ssrc).
Having that in mind I was wondering if there is a need to try to do that at all, I see that the payload type and codec information is used in jitter calculations, but if the underlying information is not valid then the end result is also not very useful.
I am also a bit confused why the mos stats are stored in the entry based on the rr->from and not entry related to rr->ssrc?

**Comment by rfuchs** [comment]
The "payload type per SSRC" is determined from the most used PT seen from that SSRC. Which might not be ideal in some fringe cases, but in the most common cases works just fine. The payload type is needed for jitter calculations because the jitter value in RTCP RRs is in "timestamp" units, but for MOS calculations the jitter in milliseconds is needed, and so the clock rate from the payload type is needed. And whether the MOS (or jitter) should be seen as the MOS produced by a sender or the MOS as reported by a receiver is debatable. For now, it's the latter.

**Comment by jerzyptak** [comment]
Thanks for the explanation.
One last thing about this function, unless I am interpreting something wrong, I think that this line
`const struct rtp_payload_type *rpt = rtp_payload_type(pt, m->codecs_recv);`
should be changed to this:
`const struct rtp_payload_type *rpt = rtp_payload_type(pt, m->codecs_send);`
