### ISSUE TITLE
Can I supply metadata on an ng delete command?

### ISSUE THREAD

**Issue by davehorton** [sipwise/rtpengine#572]
It's not quite clear to me which ng commands accept metadata -- is it just `offer` and `answer`?  I have a need to update the metadata at the end of a call, based on information that I get in the SIP BYE message, and would therefore like to supply it in the `delete` call.  Is this possible?

**Comment by rfuchs** [comment]
You're right, currently this only works for `offer` and `answer`. Can I ask the purpose of the metadata update you wish to do?

**Comment by davehorton** [comment]
I've had a few scenarios where I learn something after the call is established, which would be useful to know when I post-process the recording pcap file, and the easiest way for me to communicate that would be able to stick it in the recording metadata.  The most recent use case was that after the call started I learned from a remote system what the final file name should be -- so I wanted to be able to stick that in the metadata so that after the call was ended and I was converting pcap to mp3 I would be able to look in the metadata and get the file name the downstream consumer wanted to see

**Comment by egreenmachine** [comment]
Just my two cents. It feels like this may be the wrong place to do what you are trying to do. We are using the metadata to get initial information for the call then have our postprocessor later determine other information with an external database. The metadata is just so that we can link the call in the postprocessor to the external database. It feels like you may be overcomplicating the problem.
