### ISSUE TITLE
Issues with SDP - Error parsing c=

### ISSUE THREAD

**Issue by donfanning** [sipwise/rtpengine#58]
So I'm trying to get sipML5/Kamailio talking to OpenMCU and I'm having trouble with rtpengine completing the media loop.  The hastebin is a snippit of log.  The c= line looks fine to me so I'm not sure why it's having issues parsing it.

http://hastebin.com/ucunuzoxuv.py

**Comment by rfuchs** [comment]
Rtpengine doesn't support DNS hostnames as endpoint addresses, only IP4/6 addresses in numeric format.

**Comment by donfanning** [comment]
so https://github.com/sipwise/rtpengine/commit/50f2bfbc4dc7f73a1fa215e1c80e89ccc1887d85 can't also be added to the c line?

**Comment by rfuchs** [comment]
No, because the address/hostname in o= isn't really used for anything, it's only a matter of the parser understanding it. But the address in the c= line is used as destination address for sending RTP packets, and so rtpengine would have to perform a DNS lookup to determine the address, which isn't a trivial change to make.

**Comment by donfanning** [comment]
Ok.  I withdraw the bug.

**Comment by homepy** [comment]
> No, because the address/hostname in o= isn't really used for anything, it's only a matter of the parser understanding it. But the address in the c= line is used as destination address for sending RTP packets, and so rtpengine would have to perform a DNS lookup to determine the address, which isn't a trivial change to make.

@rfuchs 
I wonder why rtpengine "would have to perform a DNS lookup to determine the address" by itself.
It seems that if rtpengine set FQDN/DNS as the destination to send packets, the Operating System should do that for  rtpengine.
We use rtpengine in the k8s with statefulSet, use FQDN is much better than IP. Because the IP of a pod always changes, but the FQDN of a pod of a statefulSet does not.
Thanks.

**Comment by rfuchs** [comment]
> I wonder why rtpengine "would have to perform a DNS lookup to determine the address" by itself. It seems that if rtpengine set FQDN/DNS as the destination to send packets, the Operating System should do that for rtpengine. 

No it doesn't do that. The socket API requires numeric IP addresses.
