### ISSUE TITLE
No Audio on FF34

### ISSUE THREAD

**Issue by caruizdiaz** [sipwise/rtpengine#59]
When trying to interconnect FF34 to Chrome, or even FF to FF, the audio establishment fails always.

In the logs I see:

<pre>
Jan 11 15:51:45 carucloud1 rtpengine[5094]: [mlupa19ri25b4lq7099e port 32644] Successful STUN binding request from 201.141.129.19:53464
Jan 11 15:51:45 carucloud1 rtpengine[5094]: [mlupa19ri25b4lq7099e port 32644] STUN: using this candidate
Jan 11 15:51:45 carucloud1 rtpengine[5094]: [mlupa19ri25b4lq7099e port 32644] DTLS: Peer certificate accepted
Jan 11 15:51:45 carucloud1 rtpengine[5094]: [mlupa19ri25b4lq7099e port 32644] DTLS-SRTP successfully negotiated
Jan 11 15:51:45 carucloud1 rtpengine[5094]: [mlupa19ri25b4lq7099e port 32644] DTLS-SRTP successfully negotiated
Jan 11 15:51:49 carucloud1 rtpengine[5094]: [mlupa19ri25b4lq7099e port 32644] Confirmed peer address as 201.141.129.19:53464
</pre>

But, comparing to Chrome logs, the multiple "Successful STUN binding" like the following ...

<pre>
Jan 11 15:46:31 carucloud1 rtpengine[5094]: [3bkc0oqbsobnvqqk0j63 port 32510] Successful STUN binding request from 201.141.129.19:33457
Jan 11 15:46:31 carucloud1 rtpengine[5094]: [3bkc0oqbsobnvqqk0j63 port 32510] STUN: using this candidate
Jan 11 15:46:31 carucloud1 rtpengine[5094]: [3bkc0oqbsobnvqqk0j63 port 32498] Successful STUN binding request from 201.141.129.19:45243
Jan 11 15:46:31 carucloud1 rtpengine[5094]: [3bkc0oqbsobnvqqk0j63 port 32498] STUN: using this candidate
</pre>

... does not appear.

This happens browser to browser, and browser to regular UA.

**Comment by rfuchs** [comment]
Does FF advertise a zero IP address and port 9? If so, then this is fault of the new "trickle ICE" concept they've introduced, which isn't supported yet.

**Comment by caruizdiaz** [comment]
Apparently is does:
<pre>
v=0
o=Mozilla-SIPUA-35.0 4926 0 IN IP4 0.0.0.0
s=SIP Call
t=0 0
a=ice-ufrag:4e82d0c8
a=ice-pwd:3d7a88edde1e1c8b44558bf8e8d4b352
a=fingerprint:sha-256 21:D7:D8:00:F5:09:46:E8:5F:CB:9E:8C:8A:80:0F:F5:FC:AB:83:E8:B4:E7:68:4C:AE:C1:14:BA:6D:4A:D2:18
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=rtpmap:109 opus/48000/2
a=ptime:20
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=rtcp-mux
a=candidate:0 1 UDP 2130379007 192.168.3.103 57458 typ host
a=candidate:0 2 UDP 2130379006 192.168.3.103 52462 typ host
a=candidate:1 1 UDP 1694236671 201.141.23.19 2068 typ srflx raddr 192.168.3.103 rport 57458
a=candidate:1 2 UDP 1694236670 201.141.129.19 45092 typ srflx raddr 192.168.3.103 rport 52462
</pre>

So trickle ICE, is it planned to be supported by rtpengine any time soon? 

I noticed this started with FF34, and FF35 continues to have so I assume it will stay this way. Chrome however, keeps working like it used to.

Thank you for your help Richard!

**Comment by rfuchs** [comment]
It will be supported, but I can't give an ETA as I'm tied up with other projects right now.

**Comment by caruizdiaz** [comment]
Awesome, thank you!

Feel free to close the issue if another one related to trickle ICE should be created. 

Regards.

**Comment by caruizdiaz** [comment]
Just a form of documentation, I worked this issue around by SDP-mangling the c line in my SIP server (Kamailio). 

I changed connection IP from 0.0.0.0 to 127.0.0.1 (any valid IP should do it) so that rtpengine doesn't think FF is trying to "sendonly" in the SDP. As soon as I did this, everything worked fine with FF33-35.

**Comment by marcantonio** [comment]
Thanks @caruizdiaz!  That's a nice workaround.

**Comment by caruizdiaz** [comment]
@rfuchs is the one doing the magic here, @marcantonio ;)

**Comment by rfuchs** [comment]
https://github.com/sipwise/rtpengine/tree/rfuchs/trickle contains what I hope to be a quick workaround for trickle ICE to get media flowing again. Let me know how it works for you.

**Comment by caruizdiaz** [comment]
I'm sorry. I wasn't able to find time to test the patch. I will do it during the weekend probably. 

I will close de issue now, and in case the problem persist, I will reopen it to report that.

Thank you Richard!

**Comment by marcantonio** [comment]
fyi, I started using SIP.js which automatically fixes up the SDP when using Firefox.

**Comment by caruizdiaz** [comment]
I noticed they have a workaround since version 0.6.4, but I wanted to "fix" this at a lower level to support "legacy" versions of the library.

Thank you for informing. This may be useful for the community :-).

**Comment by rfuchs** [comment]
https://github.com/sipwise/rtpengine/commit/4a97bb167ac876a701a4154b1b6ec32b9758951f has been cherry picked to master

**Comment by caruizdiaz** [comment]
I just tested the patch and I'm having one way audio. Here's what I tested:

1. SAVPF to AVP, patch on: one way audio. Reapplying the workaround I used makes it work again.
2. AVP to SAVPF, patch on: one way audio. Works when applying my workaround too.
3. AVP to SAVPF, no patch applied: no audio at all, even with my workaround on.
4. SAVPF to AVP, no patch applied: no audio. Works when workaround is on.

Conclusion: works with full bidirectional audio only with patch applied and my workaround applied, both SAVPF -> AVP and AVP -> SAVPF.

**Comment by ovoshlook** [comment]
Hello. I try change media ip with rtpengine module.
Kamailio looks at sdp and try to change 0.0.0.0 address to 127.0.0.1 but rtpengine returned previous 0.0.0.0 value. 
With chrom this works perfectly

media adress is 0.0.0.0 try to change
Mar 15 01:39:28 Kamailio rtpengine[582]: Got valid command from 127.0.0.1:57966: offer - { "sdp": "v=0#015#012o=Mozilla-SIPUA-36.0 10737 0 IN IP4 0.0.0.0#015#012s=SIP Call#015#012t=0 0#015#012a=ice-ufrag:98c03b04#015#012a=ice-pwd:e3414816a3dc7ff081eb85404dfae66a#015#012a=fingerprint:sha-256 65:3A:D9:36:4C:00:4C:CC:44:DE:14:AF:70:71:F7:6B:20:B7:30:7B:A4:7D:75:98:A8:49:95:AC:8C:25:17:5A#015#012m=audio 9 RTP/SAVPF 109 9 0 8 101#015#012c=IN IP4 0.0.0.0#015#012a=rtpmap:109 opus/48000/2#015#012a=ptime:20#015#012a=rtpmap:9 G722/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8 ...
Mar 15 01:39:28 Kamailio rtpengine[582]: ... 000#015#012a=fmtp:101 0-15#015#012a=sendrecv#015#012a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level#015#012a=setup:actpass#015#012a=rtcp-mux#015#012a=candidate:0 1 UDP 2128609535 196.254.253.252 50236 typ host#015#012a=candidate:1 1 UDP 2128543999 10.0.0.10 50237 typ host#015#012a=candidate:2 1 UDP 2128478463 192.168.0.47 50238 typ host#015#012a=candidate:3 1 UDP 2128412927 192.168.56.1 50239 typ host#015#012a=candidate:4 1 UDP 2128347391 192.168.142.1 50240 typ host#015#012a=candidate:5 1 UDP 2128281855 192.168.214.1 50241 typ host#015#012a=candidate:0 2 UDP ...
Mar 15 01:39:28 Kamailio rtpengine[582]: ...  2128609534 196.254.253.252 50242 typ host#015#012a=candidate:1 2 UDP 2128543998 10.0.0.10 50243 typ host#015#012a=candidate:2 2 UDP 2128478462 192.168.0.47 50244 typ host#015#012a=candidate:3 2 UDP 2128412926 192.168.56.1 50245 typ host#015#012a=candidate:4 2 UDP 2128347390 192.168.142.1 50246 typ host#015#012a=candidate:5 2 UDP 2128281854 192.168.214.1 50247 typ host#015#012", "ICE": "remove", "DTLS": "passive", "media-address": "127.0.0.1", "flags": [ "force", "trust-address" ], "replace": [ "origin", "session-connection" ], "t ...
Mar 15 01:39:28 Kamailio rtpengine[582]: ... ransport-protocol": "RTP/AVP", "call-id": "aasfoujmcpmu7vd7b527", "received-from": [ "IP4", "85.21.140.253" ], "from-tag": "10jvnik3q5", "command": "offer" }
Mar 15 01:39:28 Kamailio rtpengine[582]: Unknown flag encountered: 'force'
Mar 15 01:39:28 Kamailio rtpengine[582]: [aasfoujmcpmu7vd7b527] Creating new call
Mar 15 01:39:28 Kamailio rtpengine[582]: [aasfoujmcpmu7vd7b527] Returning to SIP proxy: d3:sdp319:v=0#015#012o=Mozilla-SIPUA-36.0 10737 0 IN IP4 0.0.0.0#015#012s=SIP Call#015#012t=0 0#015#012m=audio 33450 RTP/AVP 109 9 0 8 101#015#012c=IN IP4 0.0.0.0#015#012a=rtpmap:109 opus/48000/2#015#012a=ptime:20#015#012a=rtpmap:9 G722/8000#015#012a=rtpmap:0 PCMU/8000#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:101 telephone-event/8000#015#012a=fmtp:101 0-15#015#012a=sendonly#015#012a=rtcp:33451#015#012a=rtcp-mux#015#0126:result2:oke

**Comment by rfuchs** [comment]
This is Firefox's "tricke ICE" implementation. Make sure you use the latest version of rtpengine.

**Comment by ovoshlook** [comment]
Stiil one side (from webphone to caller patry) sound
This is SIP dump of INVITE and OK messages
kamailio mangle-SDP 0.0.0.0 to 127.0.0.1 and then RTPengine changed media-address to needed for right RTP transaction 
(same way used by chrome. Only mangle-SDP not used because no 0.0.0.0 ip at CDP from chrome)
Webphone -> kamailio -asterisk - > provider -> called party


Invite from browser

INVITE sip:12345678900@my.service.com SIP/2.0
Via: SIP/2.0/WSS 6neafa5aiu00.invalid;branch=z9hG4bK7060048
Max-Forwards: 69
To: <sip:12345678900@my.service.com>
From: <sip:mydevice@my.service.com>;tag=vl90ockm89
Call-ID: ra90ml55cevl09qosp60
CSeq: 1433 INVITE
Proxy-Authorization: Digest algorithm=MD5, username="mydevice", realm="my.service.com", nonce="VQegclUHn0a4IoONufEoFIPtJeLZNBzE", uri="sip:12345678900@my.service.com", response="42a2665612c3097e8dd71cc626f6cb88"
Contact: <sip:sb6p854v@6neafa5aiu00.invalid;transport=ws;ob>
Content-Type: application/sdp
Session-Expires: 90
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS
Supported: timer,ice,outbound
User-Agent: JsSIP 0.6.19
Content-Length: 1286

v=0
o=Mozilla-SIPUA-36.0.1 8043 0 IN IP4 0.0.0.0
s=SIP Call
t=0 0
a=ice-ufrag:ed46161f
a=ice-pwd:394a34ba61e5f3b6d1357d4ff0e0cfa7
a=fingerprint:sha-256 E5:80:75:BB:BE:45:4A:E3:A1:BA:57:A1:BF:9C:BC:92:B7:C2:5F:17:97:C1:4A:34:D3:04:6D:AD:BA:4A:02:5F
m=audio 9 RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=rtpmap:109 opus/48000/2
a=ptime:20
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=rtcp-mux
a=candidate:0 1 UDP 2128609535 196.254.253.252 60928 typ host
a=candidate:1 1 UDP 2128543999 10.0.0.10 60929 typ host
a=candidate:2 1 UDP 2128478463 192.168.0.47 60930 typ host
a=candidate:3 1 UDP 2128412927 192.168.56.1 60931 typ host
a=candidate:4 1 UDP 2128347391 192.168.142.1 60932 typ host
a=candidate:5 1 UDP 2128281855 192.168.214.1 60933 typ host
a=candidate:0 2 UDP 2128609534 196.254.253.252 60934 typ host
a=candidate:1 2 UDP 2128543998 10.0.0.10 60935 typ host
a=candidate:2 2 UDP 2128478462 192.168.0.47 60936 typ host
a=candidate:3 2 UDP 2128412926 192.168.56.1 60937 typ host
a=candidate:4 2 UDP 2128347390 192.168.142.1 60938 typ host
a=candidate:5 2 UDP 2128281854 192.168.214.1 60939 typ host


Invite Arrived from kamailio to asterisk

<--- SIP read from UDP:10.0.1.18:5068 --->
INVITE sip:12345678900@my.service.com SIP/2.0
Record-Route: <sip:my.service.com:5068;nat=yes;ftag=vl90ockm89;lr=on>
Via: SIP/2.0/UDP my.service.com:5068;branch=z9hG4bKf707.6b2ebeee35da1153a4ea6560497bc8ed.0
Via: SIP/2.0/WSS 6neafa5aiu00.invalid;rport=63021;received=23.42.133.55;branch=z9hG4bK7060048
Max-Forwards: 69
To: <sip:12345678900@my.service.com>
From: <sip:mydevice@my.service.com>;tag=vl90ockm89
Call-ID: ra90ml55cevl09qosp60
CSeq: 1433 INVITE
Contact: <sip:sb6p854v@23.42.133.55:63021;transport=ws;ob;alias=23.42.133.55~63021~6>
Content-Type: application/sdp
Session-Expires: 90
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS
Supported: timer,ice,outbound
User-Agent: JsSIP 0.6.19
Content-Length: 1288331

v=0
o=Mozilla-SIPUA-36.0.1 8043 0 IN IP4 10.0.1.6
s=SIP Call
t=0 0
m=audio 30544 RTP/AVP 109 9 0 8 101
c=IN IP4 10.0.1.6
a=rtpmap:109 opus/48000/2
a=ptime:20
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:30545
a=rtcp-mux
127.0.0.1

Ok arrived to asterisk from called party

SIP/2.0 200 OK
Via: SIP/2.0/UDP my.service.com:5068;branch=z9hG4bKf707.6b2ebeee35da1153a4ea6560497bc8ed.0;received=10.0.1.18;rport=5068
Via: SIP/2.0/WSS 6neafa5aiu00.invalid;rport=63021;received=23.42.133.55;branch=z9hG4bK7060048
Record-Route: <sip:my.service.com:5068;nat=yes;ftag=vl90ockm89;lr=on>
From: <sip:mydevice@my.service.com>;tag=vl90ockm89
To: <sip:12345678900@my.service.com>;tag=as031ab073
Call-ID: ra90ml55cevl09qosp60
CSeq: 1433 INVITE
Server: Asterisk PBX SVN-branch-13-r432423M
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces
Contact: <sip:12345678900@10.0.1.6:50600>
Content-Type: application/sdp
Content-Length: 271

v=0
o=root 1039492800 1039492800 IN IP4 10.0.1.6
s=Asterisk PBX SVN-branch-13-r432423M
c=IN IP4 10.0.1.6
t=0 0
m=audio 18850 RTP/AVP 8 0 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=maxptime:150
a=sendrecv

Ok arrived to caller (at webphone)

SIP/2.0 200 OK
Via: SIP/2.0/WSS 6neafa5aiu00.invalid;rport=63021;received=23.42.133.55;branch=z9hG4bK7060048
Record-Route: <sip:my.service.com:5068;nat=yes;ftag=vl90ockm89;lr=on>
From: <sip:mydevice@my.service.com>;tag=vl90ockm89
To: <sip:12345678900@my.service.com>;tag=as031ab073
Call-ID: ra90ml55cevl09qosp60
CSeq: 1433 INVITE
Server: Asterisk PBX SVN-branch-13-r432423M
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces
Contact: <sip:12345678900@10.0.1.6:50600>
Content-Type: application/sdp
Content-Length: 611

v=0
o=root 1039492800 1039492800 IN IP4 my.service.com
s=Asterisk PBX SVN-branch-13-r432423M
c=IN IP4 my.service.com
t=0 0
m=audio 30564 RTP/SAVPF 8 0 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=maxptime:150
a=sendrecv
a=rtcp:30565
a=setup:passive
a=fingerprint:sha-1 09:2F:07:6E:6F:94:05:51:E4:4A:67:70:46:BE:98:05:D2:F3:69:FF
a=ice-ufrag:coIGTxVL
a=ice-pwd:qqynGPvS2hpI6NQIoigqv1HGpn
a=candidate:HQLTygKf2CCm2OiH 1 UDP 2130706431 my.service.com 30564 typ host
a=candidate:HQLTygKf2CCm2OiH 2 UDP 2130706430 my.service.com 30565 typ host

**Comment by rfuchs** [comment]
Cleaning up old tickets
