### ISSUE TITLE
 RTCP

### ISSUE THREAD

**Issue by john08burke** [sipwise/rtpengine#689]
I am trying to report call quality stats, but am running into issues with the RTCP stats not showing in either the `delete` or `query` commands.  Logs indicate a payload issue, as I am seeing a lot of `No payload type known for RTCP RR, discarding` in the logs.  Full logs posted on pastebin: [rtpengine.log](https://pastebin.com/meVWAgEV)

caller: zoiper5 (RTCP support)
callee: 3cx (no RTCP support)
version: 7.1.0.0+0~mr7.1.0.0 git-master-bb0fe2e

3cx does not support RTCP, but I was assuming that RTP Engine would still report the zoiper end that is sending the RTCP packets.  Is the packet payload just simply not supported, or is there a separate issue?

**Comment by rfuchs** [comment]
You actually do need RTCP from both sides in order to get a MOS. The reason is that latency is a part of the MOS calculation, and latency can only be determined through the 'delay since last SR' field in an SR/RR, and that is only filled in if an SR was seen from the opposite side. So I'm afraid there's not much that can be done here.
