### ISSUE TITLE
feat: need a manually set of the interface? can be automate if a only one exits

### ISSUE THREAD

**Issue by mckaygerhard** [sipwise/rtpengine#712]
**i think that trpengine must autodetect the interface if only one are available and only must be set the adtvertise interface!**

does rtpengine need a interface defined at the config file or only in the config file? and cannot be autodetected by the daemon itselft?

this due after solve my problem see in the daemon log (with many tries of filter) that:

```
Feb 25 16:28:45 ip-10-101-2-211 systemd[1]: Starting RTP/media Proxy Daemon...
Feb 25 16:28:45 ip-10-101-2-211 rtpengine[25750]: [1551112125.186388] CRIT: Fatal error: Missing option --interface
```

**Comment by rfuchs** [comment]
As per documentation (`Most of these options are indeed optional, with two exceptions. It's mandatory to specify at least one local IP address through --interface, and at least one of the --listen-... options must be given.`) we currently require the interface config to be done manually. You can specify an interface name (like `eth0`) instead of an address. I would consider a pull request that implements automatic interface config if desired (e.g. `interface=auto` or some such).

**Comment by mckaygerhard** [comment]
thanks. i read the documentation just now and receive the issue notification sorry for noise!
