### ISSUE TITLE
T.38 fails to update media relay destination on re-invite

### ISSUE THREAD

**Issue by john08burke** [sipwise/rtpengine#766]
I am running into an issue when a sip client updates their media IP on a T.38 re-invite. In the example provided, the call is established with the terminating end using media IP 6.6.6.6. The terminating end then sends a re-invite with T.38, but with updated media IP of 7.7.7.7.  However, rtpengine continues to forward media to 6.6.6.6 instead of 7.7.7.7 and the fax fails to connect. I am using "trust-address" flag to force use of SDP IPs.
<pre>
SIP Flow:
ORIG            SIP PROXY            TERM
|-------------------|-------------------|
1.1.1.1          2.2.2.2          3.3.3.3

Media Flow:
ORIG            RTPENGINE            TERM
|-------------------|-------------------|
4.4.4.4          5.5.5.5          6.6.6.6 (200)
                                  7.7.7.7 (RE-INVITE)
</pre>
Full debug log here:
[fax_rtpengine_01.log](https://github.com/sipwise/rtpengine/files/3133704/fax_rtpengine_01.log)

I also have full sip / media PCAPs that I can share privately if needed.

Thanks!

**Comment by rfuchs** [comment]
Pcap would be helpful, in particular to answer this question: In the log you can see that the incoming changed media endpoint (6.6.6.6:16628 -> 7.7.7.7:16628) also results in a change in the outgoing endpoint (5.5.5.5:15072 -> 5.5.5.5:15060). Does the receiving RTP client honour this change or does it keep sending to the original endpoint?

**Comment by john08burke** [comment]
I sent pcap privately, but posting email for ppl following:
>Hi Richard:
>Forgot to mention version: 7.1.0.0+0~mr7.1.0.0.
>
> At frame 553, the ORIG client correctly changes destination from 5.5.5.5:15060 --> 5.5.5.5:15072. Packets are, however, still being forwarded to 6.6.6.6:16628.
> 
> After looking closer at the IP sent in SDP on the re-invite, I suspect that the client is mangling the SDP incorrectly and that the IP is bogus. Nonetheless, shouldn't packets arriving on 15072 be relayed to the newly advertised IP 7.7.7.7:16628?

**Comment by rfuchs** [comment]
Actually `trust-address` probably doesn't do what you think it does (or perhaps I've misinterpreted your intentions). It's actually the default setting, and would only be negated by using the `--sip-source` command line (or config file) switch.

The problem you're seeing arises from a race condition. The re-invite switches to a unidirectional T.38 mode (only A is sending to B, but B is not sending anything to A), but shortly after the re-invite was seen, old RTP packets still arrive from B (from before B has turned its media off and switched to T.38). In this short interval, rtpengine re-learns B's endpoint address from the RTP source address and this overrides the new address seen in the SDP. The `trust-address` flag does not disable this. And since no packet ever arrives from the actual newly advertised endpoint address, the re-learned original address sticks.

However, the `asymmetric` flag does disable the learning of media endpoint address. Try using that instead of `trust-address`.

**Comment by john08burke** [comment]
Thanks for the clarification! I missed this the first time I looked at the pcap, but right after the RE-INVITE rtpengine actually does relay 1 packet to 7.7.7.7:16628 before receiving old media from 6.6.6.6:16628 and re-learning the endpoint.

I was unaware of the endpoint learning mechanisms in place with the `symmetric` flag, but this is good info to have!

**Comment by john08burke** [comment]
Closing, as not an rtpengine issue.
