### ISSUE TITLE
segfault at rtpengine master (Commit 8fb603e5c32d37e0a55e42217dfd978147cac3a2)

### ISSUE THREAD

**Issue by pkuzak** [sipwise/rtpengine#802]
Hello,

we have deployed an _rtpengine_ version built from master branch (Commit 8fb603e5c32d37e0a55e42217dfd978147cac3a2). After running for some time (several days) the application crashes with a segmentation fault.
I've attached 2 core dumps: 
[bt_full1.txt](https://github.com/sipwise/rtpengine/files/3349952/bt_full1.txt)
[bt_full2.txt](https://github.com/sipwise/rtpengine/files/3349953/bt_full2.txt)
From the back trace it looks similar like #550

**Comment by rfuchs** [comment]
Are you able to add the export `G_SLICE=always-malloc` to your startup script and run it again with that?

**Comment by pkuzak** [comment]
Yes we are. Right now it is running for a 2-3 days compiled with _-O0_ as we thought we might then get more information out of a possible dump. Would you suggest to let it run for a few more days to see whether/until it crashes or shall we stop it immediately and try your proposal?

**Comment by rfuchs** [comment]
`-O0` is a good idea, but since this seems to be a memory corruption issue, it's not very helpful as long as glib's slice allocator remains in use. So I would suggest to add the export and restart. In addition I would suggest to also set `M_CHECK_ACTION=2` if it isn't already.

**Comment by pkuzak** [comment]
I've added it and restarted: 
```
rtpproxy1-bs ~ # pidof rtpengine 2851
rtpproxy1-bs ~ # grep -ao "G_SLICE=.*" /proc/2851/environ
G_SLICE=always-mallocM_CHECK_ACTION=2
```

**Comment by ionutionita92** [comment]
Hi, 
We've got a new crash. It's a different path but the root cause seems to be the same. This time malloc generates SIGABRT because of corrupted memory when trying to allocated. You have bt full attached. I'm trying to help with this but I don't really have a clue where should I start from since I am not very familiar with rtpengine. Any hint/clue would be much appreciated. In the meantime I'm trying to look over allocated memory each time _on_redis_notification()_ is called 
[bt_full.txt](https://github.com/sipwise/rtpengine/files/3397339/bt_full.txt)

**Comment by rfuchs** [comment]
On the suspicion that this is a lurking race condition, try with the patch referenced above (f6263bf).

**Comment by ionutionita92** [comment]
We're testing it. If anything happens we'll let you know. Thank you for the help!
