### ISSUE TITLE
Module xt_RTPENGINE not found after linux kernel upgrade

### ISSUE THREAD

**Issue by juha-h** [sipwise/rtpengine#807]
On Debian, 'apt-get dist-upgrade' upgraded linux-image and reboot was needed.  After reboot, rtpengine-daemon failed to start:
```
Jul 12 13:42:34 box systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Jul 12 13:42:34 box rtpengine-iptables-setup[36791]: modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/4.9.0-9-amd64
Jul 12 13:42:34 box rtpengine-iptables-setup[36791]: iptables: No chain/target/match by that name.
Jul 12 13:42:34 box rtpengine-iptables-setup[36791]: ip6tables: No chain/target/match by that name.
Jul 12 13:42:34 box rtpengine[36806]: [1562928154.753235] ERR: FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Jul 12 13:42:34 box rtpengine[36806]: [1562928154.753710] CRIT: Userspace fallback disallowed - exiting
Jul 12 13:42:34 box systemd[1]: rtpengine-daemon.service: Main process exited, code=exited, status=255/n/a
Jul 12 13:42:35 box systemd[1]: Failed to start NGCP RTP/media Proxy Daemon.
Jul 12 13:42:35 box systemd[1]: rtpengine-daemon.service: Unit entered failed state.
Jul 12 13:42:35 box systemd[1]: rtpengine-daemon.service: Failed with result 'exit-code'.
```
I then manually reinstalled ngcp-rtpengine-kernel-dkms package in order to get new kernel module generated.

Is there some means to get a new rtpengine kernel module automatically generated when new linux-image is installed?

**Comment by rfuchs** [comment]
DKMS should handle that, but I'm unsure about the underlying mechanism. @guillemj @mika ?

**Comment by juha-h** [comment]
I'll close this now and will reopen if the same happens again.

**Comment by taurus-forever** [comment]
> DKMS should handle that, but I'm unsure about the underlying mechanism.

Just for the history here.

Normally the root of the issue is missing kernel headers, like:
https://lists.sipwise.com/pipermail/spce-user/2019-June/013838.html

Ensure package 'linux-headers-amd64' is installed,
so the new headers package will be installed automatically every time the new kernel is installed.

Have fun!

**Comment by bvisonl** [comment]
I am experiencing this issue but it is happening just when I try to enable `Homer`.

`CRIT: Userspace fallback disallowed - exiting`

If I comment out the `homer`, `homer-protocol`, and `homer-id` it works just fine.

Any ideas what is causing this?

**Comment by rfuchs** [comment]
These options are completely unrelated. Maybe a syntax error in the config file or something like that?

**Comment by bvisonl** [comment]
That was my first thought, should be completely unrelated... Here's my rtpengine.conf:

```
[rtpengine]

table = 0
interface = x.x.x.x!y.y.y.y
listen-ng = x.x.x.x:2223
timeout = 60
silent-timeout = 3600
tos = 184
foreground = true
pidfile = /etc/rtpengine/rtpengine.pid
port-min = 10000
port-max = 10099
redis = a.a.a.a:6379/0
redis-write = b.b.b.b:6379/0
redis-num-threads = 8
no-redis-required = false
redis-expires = 86400
redis-allowed-errors = -1
redis-disable-time = 10
redis-cmd-timeout = 0
redis-connect-timeout = 1000
log-level = 7
log-stderr = false
log-facility = daemon

# If I comment this out it works just fine:
homer = z.x.c.v:9060
homer-protocol = udp
homer-id = 100

```

**Comment by rfuchs** [comment]
Ok I see it. Really not related to the issue that was reported here, but fixed in c36a4458

**Comment by bvisonl** [comment]
Awesome!, I recompiled and tested it. It worked properly with that commit, thanks!.

**Comment by zizomizo84gh** [comment]
Hi Everyone,

I am trying to build the rtpengine but I am getting the following errors after starting the engine:

Apr 30 11:05:19 T450 systemd[1]: Starting NGCP RTP/media Proxy Daemon...
Apr 30 11:05:19 T450 ngcp-rtpengine-iptables-setup[1595]: modprobe: FATAL: Module xt_RTPENGINE not found in directory /lib/modules/5.8.0-50-generic
Apr 30 11:05:19 T450 ngcp-rtpengine-iptables-setup[1624]: iptables v1.8.4 (legacy): unknown option "--id"
Apr 30 11:05:19 T450 ngcp-rtpengine-iptables-setup[1624]: Try `iptables -h' or 'iptables --help' for more information.
Apr 30 11:05:19 T450 ngcp-rtpengine-iptables-setup[1634]: ip6tables v1.8.4 (legacy): unknown option "--id"
Apr 30 11:05:19 T450 ngcp-rtpengine-iptables-setup[1634]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Apr 30 11:05:19 T450 rtpengine[1636]: INFO: [crypto] Generating new DTLS certificate
Apr 30 11:05:20 T450 systemd[1]: Started NGCP RTP/media Proxy Daemon.
Apr 30 11:05:20 T450 rtpengine[1636]: ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
Apr 30 11:05:20 T450 rtpengine[1636]: INFO: [core] Startup complete, version 9.5.0.0+0~mr9.5.0.0 git-master-311069b5


Afterwards:

 I tried to make the kernel module xt_RTPENGINE alone so I get the xt_RTPENGINE.ko but unfortunately did not manage because of the following erros. 


make -C /lib/modules/5.8.0-50-generic/build M=/usr/local/src/rtpengine/kernel-module O=/lib/modules/5.8.0-50-generic/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-50-generic'
  CC [M]  /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.o
/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c: In function ‘send_proxy_packet4’:
/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:3443:42: error: passing argument 2 of ‘ip_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 3443 |  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
      |                                          ^~~
      |                                          |
      |                                          struct sk_buff *
In file included from ./include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from ./include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:28:
./include/linux/netfilter_ipv4.h:19:54: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
   19 | int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
      |                                         ~~~~~~~~~~~~~^~
/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:3443:6: error: too few arguments to function ‘ip_route_me_harder’
 3443 |  if (ip_route_me_harder(par->state->net, skb, RTN_UNSPEC))
      |      ^~~~~~~~~~~~~~~~~~
In file included from ./include/uapi/linux/netfilter_ipv4/ip_tables.h:22,
                 from ./include/linux/netfilter_ipv4/ip_tables.h:23,
                 from /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:28:
./include/linux/netfilter_ipv4.h:19:5: note: declared here
   19 | int ip_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb, unsigned addr_type);
      |     ^~~~~~~~~~~~~~~~~~
/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c: In function ‘send_proxy_packet6’:
/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:3543:43: error: passing argument 2 of ‘ip6_route_me_harder’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 3543 |  if (ip6_route_me_harder(par->state->net, skb))
      |                                           ^~~
      |                                           |
      |                                           struct sk_buff *
In file included from /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:30:
./include/linux/netfilter_ipv6.h:146:55: note: expected ‘struct sock *’ but argument is of type ‘struct sk_buff *’
  146 | int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
      |                                          ~~~~~~~~~~~~~^~
/usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:3543:6: error: too few arguments to function ‘ip6_route_me_harder’
 3543 |  if (ip6_route_me_harder(par->state->net, skb))
      |      ^~~~~~~~~~~~~~~~~~~
In file included from /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.c:30:
./include/linux/netfilter_ipv6.h:146:5: note: declared here
  146 | int ip6_route_me_harder(struct net *net, struct sock *sk, struct sk_buff *skb);
      |     ^~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
                                                                                                                                                       1,1           Top
make[2]: *** [scripts/Makefile.build:286: /usr/local/src/rtpengine/kernel-module/xt_RTPENGINE.o] Error 1
make[1]: *** [Makefile:1783: /usr/local/src/rtpengine/kernel-module] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-50-generic'
make: *** [Makefile:34: modules] Error 2


May someone advise or help to interpret this outcome.

Best regards
Abdul
