### ISSUE TITLE
Answer port changes on a re-transmission 

### ISSUE THREAD

**Issue by etamme** [sipwise/rtpengine#850]
We have found a very specific case where the port changes on an answer in response to re-transmission.  The flow is as follows:

Invite without SDP ->
<- 200 with SDP - rtpengine_offer()
...
<- 200 with SDP retransmit - rtpengine_offer()
ACK with SDP - rtpengine_answer() -> 
ACK with SDP to retransmitted 200 - rtpengine_offer() results in identical SDP EXCEPT different rports ->

There seems to be a timing element in that if the 200's are very close together, the issue does not occur, but with .3 seconds between them the issue is consistent.  

We built a client specifically to test this using sip.js and are able to reproduce at will.  

We have captured complete signalling between the proxy and rtpengine which can be viewed at: https://gist.github.com/etamme/65b9ba00e1b47a1ae392c8bf5a1476a4 

Any insight would be appreciated.

**Comment by rfuchs** [comment]
I think the address/port used for raddr/rport is wrong to begin with. I have trouble parsing and interpreting the RFC to figure out what is actually the expected behaviour here though.

But see the commit above. It should fix this inconsistency, but like I said it might still not be what it should be. (You can ignore the patch on the test script if you're using an older version.)
