### ISSUE TITLE
renegotiating ice/dtls-srtp mid-call

### ISSUE THREAD

**Issue by olivermt** [sipwise/rtpengine#88]
Hi Richard, you seem like you dont mind general questions about rtpengine so I had one for you.

I am currently trying to hack together re-INVITE in webrtc using sip.js to facilitate either adding a new screen share or for example changing what window you screen share. All of those has to be a new stream, as only mozilla supports replacing video tracks under the hood at the moment.
The problem is that you are not allowed to add and remove streams without renegotiation ice, getting new fingerprints etc etc.

The original INVITE already holds three (four, including the UDP/BFCP passthrough you already fixed up) streams, with the screen share stream disabled until we want to use it.

My idea so far was to just use the old reply-sdp from rtpengine and 'fake' a new local call which would hold the old sha-1 fingerprint that my end already generated to send to rtpengine in the first place. 

That way the new peerconnection would simply send its streams at the same ports already in use on the call on rtpengine after having set up the new stream with the screen share window you wanted to display. One problem then seems to be that the new peer connection would have a different source port on my computer, resulting in a new source port on my router. Is the source port in my router used in the dtls-srtp negotiation or can I just aim anything that matches the sha-1 hash at rtpengine and it will keep decrypting and relaying back to the new source port in the router?

Now, this is a pretty hacky solution, so my other thought is to just blindly make a reINVITE with a whole new peerConnection with fresh ice candidates in a new SDP. What I would do then is to tack on a special header that I can look at in opensips to see if the re-INVITE is simply there to replace a media stream.

Is it then possible to ONLY re-negotiate the ice / dtls-srtp between webrtc and rtpengine and leaving the legacy non-dtls side of things untouched? To get a blimp in the image while stuff re-negotiates is not a problem.

**Comment by rfuchs** [comment]
The fingerprint is only used to verify the DTLS certificate, it isn't used for SRTP encryption, so that shouldn't be a problem.

But that also means that the fingerprint is unrelated to the encryption keys being used and the keys will be different for each connection established, even if the fingerprint is the same.

More importantly, the endpoints (address and port) factor into the SRTP context and DTLS connection. If any one part of it changes, then that requires a new SRTP context (with new keys) and a new DTLS connection. While rtpengine isn't very strict about this (yet... it may be in the future) a randomly changing endpoint without resignaling is a problem, as rtpengine fixes the endpoint after a few seconds and won't look at changing addresses/ports any more after that. There's an option "media-handover" which you can enable on a per-call basis and which may do what you want, but even if it works with this, it would be a very fragile solution.

AFAIK the standards very well allow for adding and removing streams without having to renegotiate ICE or DTLS for other streams and this should work with rtpengine too. But of course that doesn't help if the WebRTC client doesn't support this.

I'm not sure what you mean with the last paragraph. If one of the parameters (ICE username for example, or DTLS fingerprint) changes, then this will be renegotiated, but this shouldn't make a different to the other side of the call (or other streams of the same side), whether it's encrypted or not.

**Comment by olivermt** [comment]
The last part in TL;DR; format is basically:

How would I renegotiate ICE with rtpengine in a SIP scenario without sending a whole re-INVITE to downstream.

Could I send INVITE from DTLS and let opensips do the control into rtpengine that does the renegotiation only on the webrtc side?

A re-INVITE that has the same SDP can be handled just fine, its SDPs with new media sources that our legacy endpoints have big trouble with (especially polycoms).

So then my follow up question is; can I send a new in-dialouge INVITE (i.e. matching to-tag etc) with the same amount of streams and have rtpengine re-use the same ports on the other side of the call?

If so, we're good.

**Comment by rfuchs** [comment]
I think I still don't quite understand what you're trying to do, so I'll give a generic reply.

During a re-invite, each media section (m= line) gets looked at separately. If none of the media/stream parameters change, then no renegotiation will occur for this media/stream and also none of the parameters on the far side will be changed. If some parameters change (for example IP/port endpoint), then these parameters will also change on the far side and this requires renegotiation. For other parameters (e.g. fingerprint), nothing will change on the far side, but the near side must be renegotiated. Again, this is done on a per-media basis, so you can have changes in one media/stream but leave others unchanged.

Rtpengine doesn't actually care whether the SDP it receives and rewrites gets sent anywhere, so you can do a fake re-invite between the SIP proxy and rtpengine to change some stream parameters but never send any SIP messages to any clients. Not sure if this is what you're alluding to.

**Comment by olivermt** [comment]
FYI, we are still working on this, we just had to complete the implementation on the client side first.

Will come back with more info when we do the actual testing after easter holidays.

Thank you for the feedback so far!

**Comment by olivermt** [comment]
re-INVITE works just fine, ports being reused and everything just fine.
