### ISSUE TITLE
quick g729b and dtmf questions

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#900]
Hello Richard

maybe they are issues already replied but i didnt find them on the list.
Are there any plans (if not already as i think) to support g729b in transcoding features? Maybe the option to set the fmtp:18 annexb(yes/no) media attributes in the SDP replied back to the offer/answer from kamailio? Or would the rtpengine be able to distinguish those params if they come in the offer/answer from kamailio, so the transcoding to/from g729b will be possible?

and for dtmf, would it be possible to use a different pyaload from dinamic 96 when using codec-transcode-telephone-event?
i think it's not possible by now.

thanks a lot and regards
david

**Comment by rfuchs** [comment]
Support for G.729 is provided by bcg729 (https://github.com/BelledonneCommunications/bcg729), which advertises itself as an annex A/B codec. So from that POV it should work. However, VAD is currently hard coded to disabled in rtpengine, and `fmtp` strings are ignored for G.729. If all that you need is to activate VAD and pass the appropriate `fmtp` then that shouldn't be too difficult. I'm only reluctant to do that because I don't have a reliable test bed for these use cases.

Re payload type, that has been asked in https://github.com/sipwise/rtpengine/issues/894. It could be added, but it hasn't been explained to me yet why it's needed.
