### ISSUE TITLE
SSRC hash table exceeded size limit  Messages started to occur

### ISSUE THREAD

**Issue by jonhvoxbox** [sipwise/rtpengine#964]
Hi Guys,

We have been running this version of rtpengine without issue for a couple of years of debian 8;
5.5.0.0+0~mr5.5.0.0 git-master-bb50729

We think due to more people working at home, we are suddenly seeing a large proportion of these messages filling up our log files (I presume due to wifi connections etc);

SSRC hash table exceeded size limit 
SRC hash table exceeded size limit (trying to add 538555805)
Apr  6 10:40:08 rtpengine-1 rtpengine: INFO: [1c6650ca05ab715e398ae1ba382429b8@192.168.x.x:5060 port 42814]: SSRC hash table exceeded size limit (trying to add 538555805)
Apr  6 10:40:08 rtpengine-1 rtpengine: INFO: [1c6650ca05ab715e398ae1ba382429b8@192.168.x.x:5060 port 42814]: SSRC hash table exceeded size limit (trying to add 538555805)

I notice from a previous post (issue 417) on a previous version mr5.4 you added a commit  (a30b47d) , would this commit apply to the version?

Also I assume we should really upgrade anyway? And if so which version would you recommend and would it resolve this issue or do I need to investigate further?

Many thanks

Jon

**Comment by rfuchs** [comment]
These messages are expected to occur if RTP clients change SSRC a lot, which some of them do (for whatever reason). The commit you mention makes sure that new SSRCs are allowed to be tracked and old ones are removed, instead of keeping new SSRCs from being added (while also defusing the log message itself). You can just update to the top of the mr5.5 branch, which includes this fix as well as several other bug fixes.

**Comment by jonhvoxbox** [comment]
Hi Richard, 

Ok perfect thanks for the response will do that.

Jon
